import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { fixture } from './simulation.test.js';
import { polygonFromPoints,turnSpot } from '../src/domain/geometry.js';
const at=(f,id)=>{const c=f.sim.repo.get(id);return [c.x,c.y,c.rotation,c.support?f.sim.repo.get(c.support).name:null];};
const settle=(f,n=80)=>{f.tick(n);for(const t of f.sim.tasks().filter(t=>t.state==='BLOCKED'))throw new Error('BLOCKED: '+t.reason);};

test('turnSpot centre anchor is an exact round trip, including odd length-minus-width',()=>{const c={envelopeLength:2001,envelopeWidth:1000};const p={x:4000,y:4000,rotation:0};const q=turnSpot(c,p);assert.deepEqual(q,{x:4500,y:3500,rotation:90});assert.deepEqual(turnSpot(c,q),p);});

test('loose stillage turns about its middle, keeps totals, writes one pickup and one placement, and turns back exactly',t=>{const f=fixture(t);const plan=f.sim.turnPreview({container:f.a.id});assert.equal(plan.ok,true,plan.message);assert.equal(plan.anchor,'CENTRE');assert.deepEqual(plan.moves[0],{container:f.a.id,x:4500,y:3500,rotation:90,support:null});assert.equal(f.sim.tasks().length,0,'preview creates nothing');console.log(plan.message);
 const r=f.cmd('rotate',{container:f.a.id,rotation:90});assert.equal(r.tasks.length,1);assert.equal(r.tasks[0].turn,true);settle(f);assert.deepEqual(at(f,f.a.id),[4500,3500,90,null]);assert.equal(f.total(),200);const led=f.sim.repo.history(500).filter(l=>l.task_id===r.tasks[0].id);assert.deepEqual(led.map(l=>l.event).sort(),['PICKUP','PLACEMENT','TURNED']);
 assert.throws(()=>f.cmd('rotate',{container:f.a.id,rotation:90}),/already been turned/);f.cmd('rotate',{container:f.a.id,rotation:0});settle(f);assert.deepEqual(at(f,f.a.id),[4000,4000,0,null]);});

test('the neighbour that used to false-block a centre turn no longer blocks it',t=>{const f=fixture(t);f.container('NB',6000,3000);const r=f.cmd('rotate',{container:f.a.id});settle(f);assert.deepEqual(at(f,f.a.id),[4500,3500,90,null]);});

test('something in the turning square moves the pivot to a corner; blocked all round is refused with names',t=>{const f=fixture(t);f.container('Pin',4100,3550,{length:300,width:300});const plan=f.sim.turnPreview({container:f.a.id});assert.equal(plan.ok,true,plan.message);assert.equal(plan.anchor,'CENTRE');assert.equal(plan.inPlace,false);console.log(plan.message);
 const g=fixture(t);g.container('N1',4000,3000);g.container('N2',4000,5000);const bad=g.sim.turnPreview({container:g.a.id});assert.equal(bad.ok,false);console.log(bad.message,JSON.stringify(bad.attempts));assert.throws(()=>g.cmd('rotate',{container:g.a.id}),/cannot be turned/);assert.equal(g.sim.tasks().length,0);});

test('a stillage flush against the fence turns by keeping a corner',t=>{const f=fixture(t);const e=f.container('Edge',8000,0);const plan=f.sim.turnPreview({container:e.id});assert.equal(plan.ok,true,plan.message);assert.equal(plan.anchor,'TL');f.cmd('rotate',{container:e.id});settle(f);assert.deepEqual(at(f,e.id),[8000,0,90,null]);});

test('a two-high pile turns as a whole in three moves; a three-high pile in five; totals kept',t=>{const f=fixture(t);const u=f.container('U',4000,4000,{support:f.a.id});const plan=f.sim.turnPreview({container:u.id});assert.equal(plan.ok,true,plan.message);assert.equal(plan.root,f.a.id);assert.deepEqual(plan.steps.map(s=>[s.name,s.park]),[['U',true],['A',false],['U',false]]);console.log(plan.message);const r=f.cmd('rotate',{container:u.id});assert.equal(r.layout.purpose,'TURN');settle(f,200);assert.deepEqual(at(f,f.a.id),[4500,3500,90,null]);assert.deepEqual(at(f,u.id),[4500,3500,90,'A']);assert.equal(f.total(),200);
 const g=fixture(t);const b2=g.container('B2',4000,4000,{support:g.a.id}),c3=g.container('C3',4000,4000,{support:b2.id});const p3=g.sim.turnPreview({container:g.a.id});assert.equal(p3.ok,true,p3.message);assert.equal(p3.steps.length,5);g.cmd('rotate',{container:g.a.id});settle(g,300);assert.deepEqual(at(g,c3.id),[4500,3500,90,'B2']);});

test('a small upper that still fits on its support turns alone and stays on it',t=>{const f=fixture(t);const s=f.container('Small',4000,4000,{support:f.a.id,length:1000,width:800});const plan=f.sim.turnPreview({container:s.id});assert.equal(plan.ok,true,plan.message);assert.equal(plan.root,s.id);assert.equal(plan.moves.length,1);f.cmd('rotate',{container:s.id});settle(f);const now=at(f,s.id);assert.equal(now[2],90);assert.equal(now[3],'A');});

test('turning works at a site with the crane, including a pile',t=>{const f=fixture(t);const mk=(name,extra={})=>f.cmd('container',{name,location:f.site.id,type:'STILLAGE',length:2000,width:1000,height:1000,tare:50000,x:4000,y:4000,...extra});const s1=mk('S1');f.cmd('rotate',{container:s1.id});settle(f);assert.deepEqual(at(f,s1.id),[4500,3500,90,null]);const s2=mk('S2',{x:4500,y:3500,rotation:90,support:s1.id});const p=f.sim.turnPreview({container:s2.id});assert.equal(p.ok,true,p.message);f.cmd('rotate',{container:s2.id});settle(f,300);assert.deepEqual(at(f,s1.id),[4000,4000,0,null]);assert.deepEqual(at(f,s2.id),[4000,4000,0,'S1']);});

test('refusals: on a truck, damaged, already moving, stocktake',t=>{const f=fixture(t);f.cmd('condition',{id:f.b.id,condition:'DAMAGED',reason:'Bent'});assert.match(f.sim.turnPreview({container:f.b.id}).message,/damaged/);f.cmd('queue',{container:f.empty.id,destination:f.truck.id});assert.match(f.sim.turnPreview({container:f.empty.id}).message,/already has a movement/);f.tick(80);assert.match(f.sim.turnPreview({container:f.empty.id}).message,/Turn it after it has been unloaded/);f.cmd('count',{scope:f.a.id});assert.match(f.sim.turnPreview({container:f.a.id}).message,/stocktake/);});

test('one running plan per yard: a second pile turn or a layout waits; loose turns do not',t=>{const f=fixture(t);f.container('U1',4000,4000,{support:f.a.id});f.container('U2',7000,4000,{support:f.b.id});f.cmd('rotate',{container:f.a.id});assert.match(f.sim.turnPreview({container:f.b.id}).message,/before turning this pile .Turn A, 0 of 3 done/);assert.throws(()=>f.cmd('commitLayout',{yard:f.yard.id,moves:[{container:f.empty.id,x:12000,y:10000,rotation:0}]}),/Finish or cancel the current layout plan/);const loose=f.cmd('rotate',{container:f.empty.id});assert.equal(loose.tasks.length,1);settle(f,400);f.cmd('rotate',{container:f.b.id});settle(f,400);assert.equal(f.sim.repo.get(f.a.id).rotation,90);assert.equal(f.sim.repo.get(f.b.id).rotation,90);assert.equal(f.sim.repo.get(f.empty.id).rotation,90);assert.equal(f.total(),200);});

test('same idempotency key does not queue a second turn',t=>{const f=fixture(t);const key=randomUUID();const a=f.cmd('rotate',{container:f.a.id,rotation:90},key),b=f.cmd('rotate',{container:f.a.id,rotation:90},key);assert.equal(a.tasks[0].id,b.tasks[0].id);assert.equal(f.sim.tasks().length,1);});

test('a boundary change keeps a turned stillage turned when it relocates',t=>{const f=fixture(t);f.cmd('rotate',{container:f.b.id});settle(f);assert.equal(f.sim.repo.get(f.b.id).rotation,90);const r=f.cmd('yard',{id:f.yard.id,points:[{x:0,y:0},{x:7000,y:0},{x:7000,y:16000},{x:0,y:16000}]});assert.ok(r.relocated.includes('B'));assert.equal(f.sim.repo.get(f.b.id).rotation,90);});

test('boundary preview is exact and leaves nothing behind',t=>{const f=fixture(t);const dump=()=>JSON.stringify([f.db.prepare('SELECT id,data,version FROM objects ORDER BY id').all(),f.db.prepare('SELECT COUNT(*) n FROM ledger').get(),f.db.prepare('SELECT * FROM contents ORDER BY container_id').all()]);const before=dump();const input={id:f.yard.id,points:[{x:0,y:0},{x:8000,y:0},{x:8000,y:16000},{x:0,y:16000}]};const q=f.sim.boundaryPreview(input);assert.equal(q.ok,true,q.message);assert.deepEqual(q.affected.map(a=>a.name).sort(),['B','Empty']);assert.equal(dump(),before);const p=f.sim.boundaryPreview({...input,detail:'full'});assert.equal(p.ok,true,p.message);assert.equal(dump(),before);console.log(JSON.stringify(p.moved.map(m=>[m.name,m.from,m.to])),p.message);const real=f.cmd('yard',input);assert.deepEqual(real.relocated.sort(),p.moved.map(m=>m.name).sort());for(const m of p.moved){const c=f.sim.repo.get(m.id);assert.deepEqual([c.x,c.y,c.rotation],[m.to.x,m.to.y,m.to.rotation]);}
 const bad=f.sim.boundaryPreview({id:f.yard.id,points:[{x:0,y:0},{x:3000,y:0},{x:3000,y:3000},{x:0,y:3000}]});assert.equal(bad.ok,false);console.log(bad.message);});

test('points boundary: extend to the left without moving stock, keep untouched float corners, refuse crossings and stale saves',t=>{const f=fixture(t);const v=f.sim.repo.get(f.yard.id).shapeRev??0;const r=f.cmd('yard',{id:f.yard.id,shapeRev:v,points:[{x:-5000,y:0},{x:20000,y:0},{x:20000,y:16000},{x:-5000,y:16000}]});assert.equal(r.relocated.length,0);assert.equal(f.sim.repo.get(f.a.id).x,4000);assert.equal(r.segments,null);assert.equal(r.area,25000*16000);
 assert.throws(()=>f.cmd('yard',{id:f.yard.id,shapeRev:v,points:r.points}),/Someone else saved/);
 const d=f.cmd('yard',{id:f.yard.id,segments:[{direction:'RIGHT',length:14000},{direction:'SE',length:2000},{direction:'DOWN',length:10000},{direction:'LEFT',length:15414}],closed:true});assert.ok(d.points.some(p=>!Number.isInteger(p.x)));const same=f.cmd('yard',{id:f.yard.id,points:d.points,name:'Renamed'});assert.deepEqual(same.points,d.points);assert.throws(()=>f.cmd('yard',{id:f.yard.id,points:d.points.map(p=>({x:p.x+0.25,y:p.y}))}),/whole number/);
 assert.throws(()=>polygonFromPoints([{x:0,y:0},{x:10000,y:10000},{x:10000,y:0},{x:0,y:10000}]),/cross/);assert.throws(()=>polygonFromPoints([{x:0,y:0},{x:10000,y:0}]),/3 and 100/);
 const fx=f.cmd('fixtures',{id:f.yard.id,fixtures:[{kind:'TOILET',x:12000,y:1000}]});assert.equal(fx.fixtures.length,1);assert.deepEqual(fx.points,same.points);});
