// The shared test yard: owner, yard, site, truck, crew and three stillages (two stocked). Kept out of any *.test.js file so
// importing it never pulls another file's tests into the importing test process.
import { randomUUID } from 'node:crypto';
import { openDatabase,atomic } from '../src/database.js';
import { Service } from '../src/service.js';
import { Simulation } from '../src/simulation.js';

// f.tick(n) runs n engine ticks. f.idle(n) runs the same ticks but stops early once nothing can change any more: no active task, no truck on the
// road, no worker or forklift walking, driving, mounting or unplaced (the scheduler's own quiescence probe in src/simulation.js), yard jobs off,
// no job still under way or cooling down (those count down even with yard jobs off) and no board order or board trip waiting. A tick then writes nothing, so the yard ends as it would after all n ticks, without paying for the idle ones.
export function fixture(t){const db=openDatabase(':memory:');t.after(()=>db.close());const auth=new Service(db);const user=auth.authenticate(auth.register({name:'Owner',companyName:'Demo',email:randomUUID()+'@example.com',password:'demonstration-password',systems:['quickstage']}));const sim=new Simulation(db,user);const cmd=(action,input={},key=randomUUID())=>sim.execute(action,input,key);const yard=cmd('yard',{name:'Yard',segments:[{direction:'RIGHT',length:20000},{direction:'DOWN',length:16000},{direction:'LEFT',length:20000}],closed:true});const products=cmd('seed');cmd('resources',{location:yard.id,workers:5,machines:1,stepMs:100,speed:100000,jobs:false});const truck=cmd('truck',{name:'T01',yard:yard.id});const site=cmd('site',{name:'Site A'});cmd('resources',{location:site.id,workers:2,machines:1,stepMs:100,speed:100000,jobs:false});const container=(name,x=4000,y=4000,extra={})=>cmd('container',{name,location:yard.id,type:'STILLAGE',length:2000,width:1000,height:1000,tare:50000,x,y,...extra});const a=container('A'),b=container('B',7000),empty=container('Empty',10000);for(const c of [a,b])cmd('opening',{container:c.id,product:products[0].id,quantity:100,reason:'DEMO ONLY opening'});const tick=(n=30)=>{for(let i=0;i<n;i++)atomic(db,()=>sim.tick(1000));};const quiet=()=>sim.jobsConfig().jobs===false&&!sim.repo.all('yard').some(y=>sim.liveJobs(y.id).some(j=>j.cooldownMs>0||['ASSIGNED','IN_PROGRESS'].includes(j.state)))&&!sim.repo.all('gameOrder').length&&!sim.repo.all('truck').some(x=>x.status==='IN_TRANSIT'||x.game)&&!sim.tasks().some(x=>!['COMPLETE','CANCELLED','FAILED','BLOCKED'].includes(x.state))&&!sim.repo.all('resource').some(r=>r.walk||r.drive||r.mountTarget||(['WORKER','FORKLIFT'].includes(r.type)&&!(Number.isFinite(r.x)&&Number.isFinite(r.y))));const idle=(n=30)=>{for(let i=0;i<n&&!quiet();i++)atomic(db,()=>sim.tick(1000));};const total=()=>sim.snapshot().balances.reduce((s,l)=>s+l.quantity,0);return {db,auth,user,sim,cmd,yard,products,truck,site,a,b,empty,container,tick,idle,total};}
// Let the yard finish (at most n ticks), retry the BLOCKED tasks, then let it finish again.
export const settle=(f,n=150)=>{f.idle(n);for(const task of f.sim.tasks().filter(t=>t.state==='BLOCKED'))f.cmd('retry',{id:task.id});f.idle(n);};
