import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { openDatabase,atomic } from '../src/database.js';
import { Service } from '../src/service.js';
import { Simulation } from '../src/simulation.js';
import { createApp } from '../src/server.js';

function create(db){const auth=new Service(db);const token=auth.register({name:'Owner',email:randomUUID()+'@example.test',companyName:'Recovery demo',password:'demonstration-password',systems:['quickstage']});const user=auth.authenticate(token),sim=new Simulation(db,user),cmd=(a,b)=>sim.execute(a,b,randomUUID());const yard=cmd('yard',{name:'Yard',closed:true,segments:[{direction:'RIGHT',length:20000},{direction:'DOWN',length:16000},{direction:'LEFT',length:20000}]});const [product]=cmd('seed',{});cmd('resources',{location:yard.id,workers:5,machines:1,stepMs:100});const truck=cmd('truck',{name:'Truck',yard:yard.id});const container=cmd('container',{name:'Pack',location:yard.id,type:'STILLAGE',length:2000,width:1000,height:1000,tare:50000,x:4000,y:4000});cmd('opening',{container:container.id,product:product.id,quantity:100,reason:'DEMO receipt'});return {auth,token,user,sim,cmd,yard,product,truck,container};}
test('disk restart during carrying preserves custody, reservations and one placement',t=>{const dir=mkdtempSync(join(tmpdir(),'scaffold-recovery-')),path=join(dir,'test.sqlite');let db=openDatabase(path);t.after(()=>{db.close();rmSync(dir,{recursive:true,force:true});});const f=create(db);const task=f.cmd('queue',{container:f.container.id,destination:f.truck.id});for(let i=0;i<9;i++)atomic(db,()=>f.sim.tick(1000));assert.equal(f.sim.repo.get(task.id).state,'CARRYING');const machine=f.sim.repo.get(f.container.id).location;db.close();db=openDatabase(path);const recovered=new Simulation(db,f.user);assert.equal(recovered.repo.get(f.container.id).location,machine);assert.equal(recovered.snapshot().trucks[0].reservedWeight,550000);for(let i=0;i<40;i++)atomic(db,()=>recovered.tick(1000));assert.equal(recovered.repo.get(f.container.id).location,f.truck.id);assert.equal(recovered.repo.quantity(f.container.id,f.product.id),100);assert.equal(recovered.repo.history(200).filter(e=>e.task_id===task.id&&e.event==='PLACEMENT').length,1);});
test('two simultaneous HTTP requests cannot claim the same container',async t=>{const db=openDatabase(':memory:'),f=create(db),server=createApp(db);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(async()=>{await new Promise(r=>server.close(r));db.close();});const url=`http://127.0.0.1:${server.address().port}/api/commands/queue`;const send=()=>fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Cookie:`session=${f.token}`,'Idempotency-Key':randomUUID()},body:JSON.stringify({container:f.container.id,destination:f.truck.id})});const responses=await Promise.all([send(),send()]);assert.deepEqual(responses.map(r=>r.status).sort(),[200,409]);assert.equal(f.sim.tasks().length,1);assert.equal(f.sim.snapshot().balances[0].reserved,100);});
test('placement rollback retains equipment custody when payload validation changes',t=>{const db=openDatabase(':memory:');t.after(()=>db.close());const f=create(db),task=f.cmd('queue',{container:f.container.id,destination:f.truck.id});for(let i=0;i<9;i++)atomic(db,()=>f.sim.tick(1000));const machine=f.sim.repo.get(f.container.id).location,truck=f.sim.repo.get(f.truck.id);truck.payload=1;f.sim.repo.save(truck);for(let i=0;i<30;i++)atomic(db,()=>f.sim.tick(1000));assert.equal(f.sim.repo.get(task.id).state,'BLOCKED');assert.equal(f.sim.repo.get(f.container.id).location,machine);assert.equal(f.sim.repo.quantity(f.container.id,f.product.id),100);assert.equal(f.sim.repo.history(200).filter(e=>e.event==='PLACEMENT').length,0);});
test('no path creates BLOCKED without pickup; count of destination blocks incoming task',t=>{const db=openDatabase(':memory:');t.after(()=>db.close());const f=create(db);for(const [name,x,y,length,width] of [['Left',3000,3000,1000,4000],['Right',6000,3000,1000,4000],['Top',4000,3000,2000,1000],['Bottom',4000,5000,2000,1000]])f.cmd('container',{name,location:f.yard.id,type:'BUNDLE',length,width,height:1000,tare:0,x,y});const task=f.cmd('queue',{container:f.container.id,destination:f.truck.id});for(let i=0;i<10;i++)atomic(db,()=>f.sim.tick(1000));assert.equal(f.sim.repo.get(task.id).state,'BLOCKED');assert.match(f.sim.repo.get(task.id).reason,/path/);assert.equal(f.sim.repo.get(f.container.id).location,f.yard.id);});
test('truck third stack level fails and site archival refuses current assets',t=>{const db=openDatabase(':memory:');t.after(()=>db.close());const f=create(db);const c=f.sim.repo.get(f.container.id);c.location=f.truck.id;c.x=0;c.y=0;f.sim.repo.save(c);const upper=f.cmd('container',{name:'Upper',location:f.yard.id,type:'STILLAGE',length:2000,width:1000,height:1000,tare:50000,x:7000,y:4000});const second=f.sim.repo.get(upper.id);second.location=f.truck.id;second.x=0;second.y=0;second.support=c.id;f.sim.repo.save(second);const third=f.cmd('container',{name:'Third',location:f.yard.id,type:'STILLAGE',length:2000,width:1000,height:1000,tare:50000,x:10000,y:4000});assert.throws(()=>f.cmd('queue',{container:third.id,destination:f.truck.id,position:{x:0,y:0,rotation:0,support:second.id}}),/Maximum 2/);const site=f.cmd('site',{name:'Site'});f.cmd('container',{name:'Empty site asset',location:site.id,type:'CAGE',length:1000,width:1000,height:1000,tare:0,x:4000,y:4000});assert.throws(()=>f.cmd('archive',{id:site.id}),/containers/);});
