import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { openDatabase,atomic } from '../src/database.js';
import { Service } from '../src/service.js';
import { Simulation,startScheduler } from '../src/simulation.js';
import { polygon,vertices,fitsPolygon } from '../src/domain/geometry.js';

export function fixture(t){const db=openDatabase(':memory:');t.after(()=>db.close());const auth=new Service(db);const user=auth.authenticate(auth.register({name:'Owner',companyName:'Demo',email:randomUUID()+'@example.com',password:'demonstration-password',systems:['quickstage']}));const sim=new Simulation(db,user);const cmd=(action,input={},key=randomUUID())=>sim.execute(action,input,key);const yard=cmd('yard',{name:'Yard',segments:[{direction:'RIGHT',length:20000},{direction:'DOWN',length:16000},{direction:'LEFT',length:20000}],closed:true});const products=cmd('seed');cmd('resources',{location:yard.id,workers:5,machines:1,stepMs:100,speed:100000});const truck=cmd('truck',{name:'T01',yard:yard.id});const site=cmd('site',{name:'Site A'});cmd('resources',{location:site.id,workers:2,machines:1,stepMs:100,speed:100000});const container=(name,x=4000,y=4000,extra={})=>cmd('container',{name,location:yard.id,type:'STILLAGE',length:2000,width:1000,height:1000,tare:50000,x,y,...extra});const a=container('A'),b=container('B',7000),empty=container('Empty',10000);for(const c of [a,b])cmd('opening',{container:c.id,product:products[0].id,quantity:100,reason:'DEMO ONLY opening'});const tick=(n=30)=>{for(let i=0;i<n;i++)atomic(db,()=>sim.tick(1000));};const total=()=>sim.snapshot().balances.reduce((s,l)=>s+l.quantity,0);return {db,auth,user,sim,cmd,yard,products,truck,site,a,b,empty,container,tick,total};}
test('true diagonal length, self intersection, irregular footprint and explicit close',()=>{const p=vertices([{direction:'SE',length:5000}])[1];assert.ok(Math.abs(Math.hypot(p.x,p.y)-5000)<0.0001);assert.throws(()=>polygon([{direction:'RIGHT',length:1000}],false));assert.throws(()=>polygon([{direction:'SE',length:5000},{direction:'LEFT',length:3500},{direction:'NE',length:5000}],true));const poly=[{x:0,y:0},{x:6000,y:0},{x:6000,y:2000},{x:2000,y:2000},{x:2000,y:6000},{x:0,y:6000}];assert.equal(fitsPolygon({x:1000,y:1000,w:4000,h:4000},poly),false);});
test('reservation, pickup custody, completion, idempotency and total conservation',t=>{const f=fixture(t),key=randomUUID();const task=f.cmd('queue',{container:f.a.id,destination:f.truck.id},key);assert.equal(f.total(),200);assert.equal(f.sim.snapshot().balances.find(l=>l.container===f.a.id).reserved,100);assert.equal(f.cmd('queue',{container:f.a.id,destination:f.truck.id},key).id,task.id);f.tick(9);const current=f.sim.repo.get(task.id);assert.equal(current.state,'CARRYING');assert.equal(f.sim.repo.get(f.a.id).location,current.machine);assert.equal(f.total(),200);assert.throws(()=>f.cmd('cancel',{id:task.id}),/cannot teleport/);f.tick();assert.equal(f.sim.repo.get(f.a.id).location,f.truck.id);assert.equal(f.total(),200);const ledger=f.sim.repo.history(200).filter(l=>l.task_id===task.id);assert.equal(ledger.filter(l=>l.event==='PICKUP').length,1);assert.equal(ledger.filter(l=>l.event==='PLACEMENT').length,1);f.tick();assert.equal(f.sim.repo.history(200).filter(l=>l.task_id===task.id).length,2);});
test('exact full and partial allocation, delivery, partial unload and return loop',t=>{const f=fixture(t);const request=f.cmd('request',{site:f.site.id,product:f.products[0].id,quantity:120});f.cmd('allocate',{id:request.id,truck:f.truck.id});f.tick(100);let blocked=f.sim.tasks().filter(t=>t.state==='BLOCKED');for(const task of blocked)f.cmd('retry',{id:task.id});f.tick(100);assert.deepEqual(f.sim.tasks().filter(t=>t.state==='BLOCKED').map(t=>t.reason),[]);assert.equal(f.sim.repo.quantity(f.b.id,f.products[0].id),80);assert.equal(f.sim.repo.quantity(f.empty.id,f.products[0].id),20);assert.equal(f.total(),200);f.cmd('dispatch',{id:f.truck.id,destination:f.site.id});assert.equal(f.sim.snapshot().balances.filter(l=>l.location===f.site.id).length,0);f.tick(5);assert.equal(f.sim.snapshot().balances.filter(l=>l.location===f.site.id).length,0);f.cmd('queue',{container:f.a.id,destination:f.site.id});f.tick();assert.equal(f.sim.snapshot().balances.filter(l=>l.location===f.site.id).reduce((s,l)=>s+l.quantity,0),100);assert.equal(f.sim.repo.get(f.empty.id).location,f.truck.id);f.cmd('unload',{id:f.truck.id});f.tick();assert.equal(f.sim.repo.get(request.id).status,'DELIVERED');f.cmd('returnStock',{container:f.a.id,truck:f.truck.id});f.tick();f.cmd('returnStock',{container:f.empty.id,truck:f.truck.id});f.tick();f.cmd('dispatch',{id:f.truck.id,destination:f.yard.id});f.tick(5);f.cmd('unload',{id:f.truck.id});f.tick(60);for(const task of f.sim.tasks().filter(t=>t.state==='BLOCKED'))f.cmd('retry',{id:task.id});f.tick(60);assert.equal(f.total(),200);assert.equal(f.sim.snapshot().balances.filter(l=>l.location===f.yard.id).reduce((s,l)=>s+l.quantity,0),200);});
test('payload includes tare once; at capacity succeeds; queued overbooking fails atomically',t=>{const f=fixture(t);const truck=f.sim.repo.get(f.truck.id);truck.payload=550000;f.sim.repo.save(truck);f.cmd('queue',{container:f.a.id,destination:truck.id});assert.equal(f.sim.snapshot().trucks[0].reservedWeight,550000);assert.throws(()=>f.cmd('queue',{container:f.b.id,destination:truck.id}),/payload|footprint/);assert.equal(f.sim.tasks().length,1);f.tick();assert.equal(f.sim.snapshot().trucks[0].loadedWeight,550000);});
test('overlap, oversize, unsupported stacks, lower container and height rules',t=>{const f=fixture(t);assert.throws(()=>f.container('Overlap',4000,4000),/overlap/);assert.throws(()=>f.container('Unsupported',12000,4000,{support:'missing'}),/support/);const upper=f.container('Upper',4000,4000,{support:f.a.id});assert.throws(()=>f.cmd('queue',{container:f.a.id,destination:f.truck.id}),/top stillage/);assert.throws(()=>f.cmd('queue',{container:upper.id,destination:f.truck.id,position:{x:5500,y:0,rotation:0}}),/envelope/);let support=upper;for(let i=3;i<=7;i++)support=f.container('Stack '+i,4000,4000,{support:support.id});assert.throws(()=>f.container('Eighth',4000,4000,{support:support.id}),/Maximum 7/);});
test('no equipment blocks; busy equipment queues fairly without double booking',t=>{const f=fixture(t);f.cmd('resources',{location:f.yard.id,workers:0,machines:0});const task=f.cmd('queue',{container:f.a.id,destination:f.truck.id});f.tick();assert.equal(f.sim.repo.get(task.id).state,'BLOCKED');assert.match(f.sim.repo.get(task.id).reason,/forklift/);f.cmd('resources',{location:f.yard.id,workers:5,machines:1});f.cmd('retry',{id:task.id});const second=f.cmd('queue',{container:f.b.id,destination:f.truck.id});f.tick(3);const resources=f.sim.repo.all('resource').filter(r=>r.task);assert.equal(new Set(resources.map(r=>r.id)).size,resources.length);assert.equal(resources.length,2);assert.equal(f.sim.repo.get(second.id).state,'RESERVED');assert.throws(()=>f.cmd('resources',{location:f.yard.id,workers:0,machines:0}),/busy/);f.tick(80);assert.equal(f.sim.repo.get(second.id).state,'COMPLETE');});
test('cancel before pickup releases stock and destination reservations',t=>{const f=fixture(t);const task=f.cmd('queue',{container:f.a.id,destination:f.truck.id});f.cmd('cancel',{id:task.id});assert.equal(f.sim.snapshot().balances.find(l=>l.container===f.a.id).reserved,0);assert.equal(f.sim.snapshot().trucks[0].reservedWeight,0);assert.equal(f.sim.repo.get(f.a.id).location,f.yard.id);});
test('unknown weight and pack settings block only affected operation; provenance conflicts fail',t=>{const f=fixture(t);f.cmd('opening',{container:f.empty.id,product:f.products[2].id,quantity:5,reason:'Demo unknown'});assert.throws(()=>f.cmd('queue',{container:f.empty.id,destination:f.truck.id}),/unknown/);const r=f.cmd('request',{site:f.site.id,product:f.products[2].id,quantity:1});assert.throws(()=>f.cmd('allocate',{id:r.id,truck:f.truck.id}),/Full-pack/);assert.throws(()=>f.cmd('product',{name:'Duplicate',reference:'DEMO-L2000',system:'quickstage',verification:'DEMO ONLY'}),/conflicting/);f.auth.updateCompany(f.user,{name:'Demo',systems:['at-pac']});assert.equal(f.total(),205);assert.equal(f.sim.snapshot().products.length,3);});
test('stocktake locks scope, requires reason and permission, records variance',t=>{const f=fixture(t);const count=f.cmd('count',{scope:f.a.id});assert.throws(()=>f.cmd('queue',{container:f.a.id,destination:f.truck.id}),/stocktake/);assert.throws(()=>f.cmd('observe',{id:count.id,observed:[95],reason:''}),/reason/);f.cmd('observe',{id:count.id,observed:[95],reason:'Five missing in demonstration count'});f.cmd('approveCount',{id:count.id});assert.equal(f.total(),195);assert.equal(f.sim.repo.history(200).filter(l=>l.event==='STOCKTAKE_ADJUSTMENT')[0].quantity,-5);assert.throws(()=>f.db.prepare('DELETE FROM ledger').run(),/append only/);});
test('tenant guessed IDs, supervisor site scope and adjustment permission',t=>{const f=fixture(t);f.auth.addUser(f.user,{name:'Supervisor',email:'supervisor@example.com',password:'demonstration-password',roles:['SUPERVISOR']});const supervisor=f.auth.authenticate(f.auth.login({email:'supervisor@example.com',password:'demonstration-password'}));const restricted=new Simulation(f.db,supervisor);assert.equal(restricted.snapshot().sites.length,0);assert.throws(()=>restricted.execute('request',{site:f.site.id,product:f.products[0].id,quantity:1},randomUUID()),/assigned/);assert.throws(()=>restricted.execute('approveCount',{id:'guessed'},randomUUID()),{status:403});const other=f.auth.authenticate(f.auth.register({name:'Other',companyName:'Other',email:'other@example.com',password:'demonstration-password',systems:['quickstage']}));const isolated=new Simulation(f.db,other);assert.throws(()=>isolated.execute('queue',{container:f.a.id,destination:f.truck.id},randomUUID()),{status:404});assert.equal(isolated.snapshot().balances.length,0);assert.ok(!isolated.export('stock').includes('DEMO ledger'));});
test('archival retains history and refuses occupied sites; engine singleton guard',t=>{const f=fixture(t);f.cmd('archive',{id:f.site.id});assert.equal(f.sim.repo.get(f.site.id).status,'ARCHIVED');assert.ok(f.sim.repo.history(200).some(l=>l.event==='SITE_ARCHIVED'));const stop=startScheduler(f.db);assert.throws(()=>startScheduler(f.db),/Another movement engine/);stop();});
test('placement input cannot overwrite identity, custody, tare or content',t=>{const f=fixture(t);f.cmd('queue',{container:f.a.id,destination:f.truck.id,position:{x:0,y:0,rotation:0,id:'forged',location:f.site.id,tare:0}});f.tick();const c=f.sim.repo.get(f.a.id);assert.equal(c.id,f.a.id);assert.equal(c.location,f.truck.id);assert.equal(c.tare,50000);assert.equal(f.total(),200);});
test('active destination count prevents incoming movement reservations',t=>{const f=fixture(t);f.cmd('queue',{container:f.a.id,destination:f.truck.id});f.tick();f.cmd('count',{scope:f.yard.id});assert.throws(()=>f.cmd('queue',{container:f.a.id,destination:f.yard.id}),/stocktake/);assert.equal(f.sim.repo.get(f.a.id).location,f.truck.id);assert.equal(f.total(),200);});
test('cancelling a request releases its exact unstarted reservations and deck claims',t=>{const f=fixture(t);const request=f.cmd('request',{site:f.site.id,product:f.products[0].id,quantity:120});f.cmd('allocate',{id:request.id,truck:f.truck.id});f.cmd('cancelRequest',{id:request.id,reason:'Demonstration request cancelled'});assert.equal(f.sim.snapshot().reservedTotal,0);assert.equal(f.sim.snapshot().trucks[0].reservedWeight,0);assert.equal(f.sim.tasks().filter(t=>t.state!=='CANCELLED').length,0);assert.equal(f.total(),200);});
test('reviewed catalogue batch conflicts roll back all new variants and provenance',t=>{const f=fixture(t);const before=f.sim.repo.all('source').length;assert.throws(()=>f.cmd('importCatalogue',{name:'Reviewed test batch',products:[{name:'New demo',reference:'NEW-DEMO',system:'quickstage',verification:'DEMO ONLY'},{name:'Conflicting',reference:'DEMO-L2000',system:'quickstage',verification:'DEMO ONLY'}]}),/conflicting/);assert.equal(f.sim.repo.all('product').length,3);assert.equal(f.sim.repo.all('source').length,before);assert.equal(f.sim.repo.all('importBatch').length,0);});

test('parking dimensions persist independently of storage and reject invalid sizes',t=>{const f=fixture(t);const saved=f.cmd('parking',{id:f.yard.id,side:'RIGHT',vehicleLength:9000,vehicleWidth:2100,clearance:500});assert.equal(saved.parking.length,10000);assert.equal(saved.parking.width,3100);assert.equal(saved.area,f.yard.area);assert.equal(f.sim.snapshot().yards[0].parking.width,3100);assert.throws(()=>f.cmd('parking',{id:f.yard.id,side:'RIGHT',vehicleLength:-1,vehicleWidth:2100,clearance:500}));assert.equal(f.sim.snapshot().yards[0].parking.length,10000);assert.equal(f.total(),200);});
test('home availability excludes damaged stock and counts cages across storage',t=>{const f=fixture(t);f.container('Fittings cage',13000,4000,{type:'CAGE',length:1200});f.cmd('condition',{id:f.a.id,condition:'DAMAGED',reason:'Inspection'});const summary=f.sim.snapshot().availability;assert.equal(summary.cages,1);assert.equal(summary.stillages,3);assert.equal(summary.serviceablePieces,100);});
