import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { fixture } from './simulation.test.js';
import { Simulation } from '../src/simulation.js';
import { polygonFromPoints,turnPath } from '../src/domain/geometry.js';
import { ringProblems,cleanCorners } from '../public/shape.js';
const at=(f,id)=>{const c=f.sim.repo.get(id);return [c.x,c.y,c.rotation,c.support?f.sim.repo.get(c.support).name:null];};
const settle=(f,n=80)=>{f.tick(n);for(const t of f.sim.tasks().filter(t=>t.state==='BLOCKED'))throw new Error('BLOCKED: '+t.reason);};

test('a stillage in a flush row is carried out, turned in open ground and set back turned where it stood',t=>{const f=fixture(t);const l=f.container('L',3500,1000),m=f.container('M',5500,1000),r=f.container('R',7500,1000);const plan=f.sim.turnPreview({container:m.id});assert.equal(plan.ok,true,plan.message);assert.equal(plan.anchor,'CENTRE');assert.equal(plan.inPlace,false);assert.match(plan.message,/carry it to open ground/);const res=f.cmd('rotate',{container:m.id});f.tick(3);const task=f.sim.repo.get(res.tasks[0].id);assert.ok(task.path.length>2);assert.ok(task.turnAt);settle(f);assert.deepEqual(at(f,m.id),[6000,500,90,null]);assert.deepEqual(at(f,l.id),[3500,1000,0,null]);assert.deepEqual(at(f,r.id),[7500,1000,0,null]);assert.equal(f.total(),200);});

test('turnPath returns null when no clear circle fits anywhere',()=>{const poly=[{x:0,y:0},{x:2500,y:0},{x:2500,y:2500},{x:0,y:2500}];const c={envelopeLength:2000,envelopeWidth:1000};assert.equal(turnPath(poly,c,{x:0,y:0,rotation:0},{x:0,y:0,rotation:90},[{x:2000,y:2000,w:500,h:500}]),null);});

test('turning back after a corner-anchored turn restores the exact original spot',t=>{const f=fixture(t);const e=f.container('Edge',8000,0);f.cmd('rotate',{container:e.id});settle(f);assert.deepEqual(at(f,e.id),[8000,0,90,null]);const back=f.sim.turnPreview({container:e.id});assert.equal(back.anchor,'BACK');f.cmd('rotate',{container:e.id,rotation:0});settle(f);assert.deepEqual(at(f,e.id),[8000,0,0,null]);});

test('an empty stillage turn leaves a TURNED audit row; a no-op reposition is refused',t=>{const f=fixture(t);const r=f.cmd('rotate',{container:f.empty.id});settle(f);assert.equal(f.sim.repo.history(500).filter(l=>l.event==='TURNED'&&l.container_id===f.empty.id).length,1);const c=f.sim.repo.get(f.empty.id);assert.throws(()=>f.cmd('queue',{container:c.id,destination:f.yard.id,position:{x:c.x,y:c.y,rotation:c.rotation,support:null}}),/already there/);assert.equal(f.sim.snapshot().recentTasks.find(x=>x.id===r.tasks[0].id).title,'Turn Empty');});

test('layouts keeps every running plan in view after many closed ones and still enforces one running plan',t=>{const f=fixture(t);for(let i=0;i<11;i++){f.cmd('rotate',{container:f.empty.id,rotation:(i%2)?0:90});settle(f);}const plan=f.cmd('commitLayout',{yard:f.yard.id,moves:[{container:f.b.id,x:12000,y:10000,rotation:0}]});assert.ok(f.sim.layouts().some(l=>l.id===plan.layout.id&&l.status==='ACTIVE'));assert.throws(()=>f.cmd('commitLayout',{yard:f.yard.id,moves:[{container:f.a.id,x:12000,y:12000,rotation:0}]}),/Finish or cancel the current layout plan/);});

test('rotate needs operations.manage and the preview writes nothing',t=>{const f=fixture(t);const before=[f.sim.tasks().length,f.sim.repo.history(1000).length];const p=f.sim.turnPreview({container:f.a.id});assert.equal(p.ok,true);assert.deepEqual([f.sim.tasks().length,f.sim.repo.history(1000).length],before);f.auth.addUser(f.user,{name:'Supervisor',email:'sup@example.com',password:'demonstration-password',roles:['SUPERVISOR']});const sup=f.auth.authenticate(f.auth.login({email:'sup@example.com',password:'demonstration-password'}));const s=new Simulation(f.db,sup);assert.throws(()=>s.execute('rotate',{container:f.a.id},randomUUID()),{status:403});assert.throws(()=>s.turnPreview({container:f.a.id}),{status:403});assert.throws(()=>s.boundaryPreview({id:f.yard.id}),{status:403});});

test('corner validation: duplicates, spikes, too many, not objects, whole millimetres',()=>{assert.throws(()=>polygonFromPoints([{x:0,y:0},{x:0,y:0},{x:1000,y:0},{x:1000,y:1000}]),/no length/);assert.throws(()=>polygonFromPoints([{x:0,y:0},{x:2000,y:0},{x:1000,y:0},{x:1000,y:1000}]),/folds back|cross/);assert.throws(()=>polygonFromPoints(Array.from({length:101},(_,i)=>({x:i*10,y:(i%2)*10}))),/between 3 and 100/);assert.throws(()=>polygonFromPoints([{x:0,y:0},5,{x:0,y:10}]),{status:400});assert.throws(()=>polygonFromPoints([{x:0,y:0},{x:10.5,y:0},{x:0,y:10}]),{status:400});assert.equal(ringProblems([{x:0,y:0},{x:10,y:0},{x:10,y:10},{x:0,y:10}]).length,0);assert.equal(cleanCorners([{x:0,y:0},{x:10,y:0},{x:10,y:10},{x:0,y:0}]).points.length,3);});

test('rename-only, height-only and grow-only saves stop nobody and move nothing; a shrink still does',t=>{const f=fixture(t);const w=f.sim.snapshot().resources.find(r=>r.type==='WORKER'&&r.location===f.yard.id);f.cmd('workerCommand',{id:w.id,order:'MOVE',x:15000,y:12000});f.tick(2);assert.ok(f.sim.repo.get(w.id).walk);const r1=f.cmd('yard',{id:f.yard.id,name:'Renamed'});assert.equal(r1.message,'Saved.');assert.ok(f.sim.repo.get(w.id).walk,'still walking after rename');const r2=f.cmd('yard',{id:f.yard.id,height:9000});assert.equal(r2.message,'Saved.');assert.equal(r2.height,9000);assert.ok(f.sim.repo.get(w.id).walk,'still walking after height change');const pts=f.sim.repo.get(f.yard.id).points.map(p=>({...p}));pts[1].x=21000;pts[2].x=21000;assert.equal(f.cmd('yard',{id:f.yard.id,points:pts}).message,'Saved.');assert.ok(f.sim.repo.get(w.id).walk,'still walking after the yard only grew');pts[1].x=19000;pts[2].x=19000;f.cmd('yard',{id:f.yard.id,points:pts});assert.equal(f.sim.repo.get(w.id).walk,null);});

test('new yards and sites get a gate clear of the loading zone, so the first save reports no gate move',t=>{const f=fixture(t);const y=f.sim.repo.get(f.yard.id);assert.deepEqual(y.gate,{x:3500,y:1000});const s=f.sim.repo.get(f.site.id);assert.deepEqual(s.gate,{x:3500,y:1000});const pts=y.points.map(p=>({...p}));pts[2].y=17000;pts[3].y=17000;const r=f.cmd('yard',{id:y.id,points:pts});assert.doesNotMatch(r.message,/Gate moved/);});

test('boundary preview: quick lists the affected stock without moving it; archived sites are refused',t=>{const f=fixture(t);const q=f.sim.boundaryPreview({id:f.yard.id,points:[{x:0,y:0},{x:6500,y:0},{x:6500,y:16000},{x:0,y:16000}]});assert.equal(q.ok,true,q.message);assert.deepEqual(q.affected.map(a=>[a.name,a.why]).sort(),[['B','outside'],['Empty','outside']]);assert.equal(f.sim.repo.get(f.b.id).x,7000);const b=f.cmd('site',{name:'Site B'});f.cmd('archive',{id:b.id});const p=f.sim.boundaryPreview({id:b.id,points:[{x:0,y:0},{x:9000,y:0},{x:9000,y:9000},{x:0,y:9000}]});assert.equal(p.ok,false);assert.match(p.message,/active site/);const n=f.sim.boundaryPreview({name:'New',points:[{x:0,y:0},{x:9000,y:0},{x:9000,y:9000},{x:0,y:9000}]});assert.equal(n.ok,true);assert.equal(f.sim.repo.all('yard').length,1);});

test('fixture ids survive saves; duplicates and new fixtures get fresh ids',t=>{const f=fixture(t);const r=f.cmd('fixtures',{id:f.yard.id,fixtures:[{id:'F7',kind:'TOILET',x:14000,y:1000},{kind:'TOILET',x:16000,y:1000},{id:'F7',kind:'TOILET',x:14000,y:12000}]});assert.deepEqual(r.fixtures.map(x=>x.id),['F7','F1','F2']);const again=f.cmd('fixtures',{id:f.yard.id,fixtures:r.fixtures.map(x=>({...x,name:x.name+' renamed'}))});assert.deepEqual(again.fixtures.map(x=>x.id),['F7','F1','F2']);});

test('automatic placement follows a yard that no longer starts at the origin',t=>{const f=fixture(t);f.cmd('yard',{id:f.yard.id,points:[{x:-30000,y:0},{x:20000,y:0},{x:20000,y:16000},{x:-30000,y:16000}]});const draft={name:'P',type:'STILLAGE',length:2000,width:1000,height:1000,envelopeLength:2000,envelopeWidth:1000,tare:1,rotation:0};const p=f.sim.positionFor(draft,f.yard.id);assert.equal(p.x,-26500);assert.equal(p.y,1000);});

test('re-sending the same corners in another order or direction is not a shape change',t=>{const f=fixture(t);const w=f.sim.snapshot().resources.find(r=>r.type==='WORKER'&&r.location===f.yard.id);f.cmd('workerCommand',{id:w.id,order:'MOVE',x:15000,y:12000});f.tick(2);const pts=f.sim.repo.get(f.yard.id).points;const r=f.cmd('yard',{id:f.yard.id,name:'Same',points:[pts[2],pts[1],pts[0],pts[3]]});assert.equal(r.message,'Saved.');assert.ok(f.sim.repo.get(w.id).walk);});
