import { integer,requireRule,rect,overlap,fitsPolygon,route } from './geometry.js';
import { label } from './catalogue.js';
import { active } from './inventory.js';
// Yard jobs: the work a yard hand does between forklift moves. Every worker has every skill unless switched off; the automatic
// assigner hands out real jobs derived from the yard state by priority ladder, then routine work so nobody stands still.
export const SKILLS=[
 {code:'TRUCK',label:'Truck operations',short:'Trucks',priority:1,routine:false,vocabulary:['load trucks','unload returns','verify loads against pick tickets','strap/unstrap loads','stage outgoing loads','photograph completed loads','check quantities','report shortages/damage']},
 {code:'ORDERS',label:'Order preparation',short:'Orders',priority:2,routine:false,vocabulary:['pick material for upcoming jobs',"pre-stage tomorrow's loads",'build job-specific stillages/packs','double-check picked quantities','label loads/stillages','separate priority/urgent jobs','prepare backloads/transfers']},
 {code:'RETURNS',label:'Returns processing',short:'Returns',priority:4,routine:false,vocabulary:['count returned material','identify damaged material','separate serviceable/unserviceable stock','return good stock to storage locations','quarantine damaged equipment','record missing material','remove concrete/mud/tape/tags where appropriate']},
 {code:'HANDLING',label:'Material handling',short:'Handling',priority:5,routine:false,vocabulary:['restack material','fill stillages','consolidate half-full stillages','separate mixed stillages','break down returned loads','move material into correct bays','prepare empty stillages','straighten poorly stacked material','sort tube by length/type','sort fittings/accessories']},
 {code:'STOCK',label:'Stock control',short:'Stock',priority:6,routine:false,vocabulary:['cycle counts','check stillage quantities','identify low stock','investigate misplaced stock','correct location labels','count high-use components','verify physical stock against system quantities','flag excess/slow-moving stock']},
 {code:'YARD',label:'Yard organisation',short:'Yard',priority:7,routine:true,vocabulary:['clean yard','sweep loading zones','clear access ways','organise storage bays','keep forklift routes clear','move empty pallets/stillages','stack dunnage','remove rubbish','organise straps/chains/timber','maintain designated scrap areas']},
 {code:'EQUIPMENT',label:'Equipment checks',short:'Equipment',priority:7,routine:true,vocabulary:['forklift/pre-start support','inspect stillages for damage','check lifting points','check straps/chains','inspect racks/storage areas','report damaged pallets or cages','check signage and barriers']},
 {code:'SAFETY',label:'Safety tasks',short:'Safety',priority:7,routine:true,vocabulary:['remove trip hazards','check pedestrian walkways','inspect load stability','maintain exclusion zones','clean spills','check emergency access','report hazards','correct unsafe stacks','verify maximum stack heights']},
 {code:'MAINTENANCE',label:'Maintenance/preparation',short:'Maintenance',priority:8,routine:true,vocabulary:['clean reusable components','remove excessive concrete/debris','lubricate suitable moving components','straighten/organise equipment where authorised','prepare damaged material for repair','prepare scrap for disposal']},
 {code:'IMPROVEMENT',label:'Continuous improvement',short:'Improvement',priority:8,routine:true,vocabulary:['identify wasted travel','reorganise frequently used stock closer to loading areas','mark permanent bay locations','improve stillage layouts','review loading sequence','identify repeated shortages/errors','suggest better storage methods']},
];
export const LADDER=[[1,'Trucks waiting / hazards'],[2,'Loads required today'],[3,"Tomorrow's loads"],[4,'Returned material'],[5,'Refill / consolidate stillages'],[6,'Stock counts'],[7,'Yard organisation'],[8,'Cleaning and improvement work']].map(([priority,label])=>({priority,label}));
export const skillOn=(w,code)=>w?.skills?.[code]!==false;
const SKILL=Object.fromEntries(SKILLS.map(s=>[s.code,s]));
const LIVE=['OPEN','ASSIGNED','IN_PROGRESS','BLOCKED'];
const ISO=()=>new Date().toISOString();
const REAL=new Set(['UNLOAD','CONSOLIDATE','SORT','STACK']),CHECK=new Set(['LOAD_CHECK','PRECHECK']);
const badgeOf=effect=>REAL.has(effect)?'REAL':CHECK.has(effect)?'CHECK':'RECORDED';
const clocks=new Map(),faults=new Map();
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const spot=(zone)=>({x:zone.x+750,y:zone.y+500});
export const jobMethods={
  skillCatalogue(){return SKILLS;},
  normalisedSkills(w){const out={};for(const s of SKILLS)out[s.code]=skillOn(w,s.code);return out;},
  jobsConfig(){return this.repo.all('config')[0]??{};},
  // Forklift moves on the same ladder: truck work (and the repacks that feed it) is P1, layout steps P7, other moves P5.
  taskInfo(t){const kind=id=>{try{return this.repo.get(id).kind;}catch{return 'unknown';}};const truck=!!t.request||kind(t.from)==='truck'||kind(t.to)==='truck';const priority=truck?1:t.layout||t.turn?7:5;const skill=truck?'TRUCK':t.layout||t.turn?'YARD':'HANDLING';const n=id=>{try{return this.repo.get(id).name;}catch{return 'stock';}};const c=n(t.container);const title=t.type==='REPACK'?'Repack '+t.quantity+' × '+n(t.product)+' from '+n(t.sourceContainer)+' into '+c:kind(t.to)==='truck'?'Load '+n(t.to)+' – '+c:kind(t.from)==='truck'?'Unload '+n(t.from)+' – '+c:t.turn&&!t.layout?'Turn '+c:t.turn?(t.park?'Set '+c+' down for a pile turn (step '+t.step+')':'Pile turn step '+t.step+' – '+c):t.layout?'Layout step '+t.step+' – '+c:'Move '+c;return {priority,skill,title};},
  taskPriority(t){return this.taskInfo(t).priority;},
  liveJobs(yardId){return this.repo.all('job').filter(j=>j.yard===yardId&&LIVE.includes(j.state));},
  jobObstacles(yard){return [...this.workerObstacles(yard.id),...this.repo.all('resource').filter(r=>r.enabled&&r.type==='FORKLIFT'&&r.location===yard.id&&r.task&&Number.isFinite(r.x)).map(r=>({x:r.x,y:r.y,...this.forkliftShape(r)}))];},
  standingSpot(box,yard,obstacles){const tries=[];for(const d of [100,600,1100,1600,2100])tries.push({x:box.x-500-d,y:box.y},{x:box.x+box.w+d,y:box.y},{x:box.x,y:box.y-500-d},{x:box.x,y:box.y+box.h+d},{x:box.x+box.w+d,y:box.y+box.h+d},{x:box.x-500-d,y:box.y-500-d});for(const p of tries){const r={x:Math.round(p.x),y:Math.round(p.y),w:500,h:500};if(fitsPolygon(r,yard.points)&&!obstacles.some(o=>overlap(r,o)))return {x:r.x,y:r.y};}return null;},
  // A move order can name a place instead of coordinates: loading, gate, a stillage, a forklift or a fixture at the worker's location.
  resolveTarget(worker,target){
    const loc=this.repo.get(worker.location);requireRule(loc.kind==='yard'||loc.kind==='site','The worker is not at a yard or site.');
    if(worker.mountedOn){const machine=this.repo.get(worker.mountedOn,'resource'),shape=this.forkliftShape(machine),obstacles=this.forkliftObstacles(machine);
      if(target==='loading'||target==='gate'){const z=target==='loading'?loc.loading:loc.gate;const tries=[{x:z.x-shape.w-300,y:z.y},{x:z.x+2300,y:z.y},{x:z.x,y:z.y-shape.h-300},{x:z.x,y:z.y+1800}];for(const p of tries){const r={...p,...shape};if(fitsPolygon(r,loc.points)&&!obstacles.some(o=>overlap(r,o)))return p;}requireRule(false,'No clear forklift route to the '+(target==='loading'?'loading zone':'gate')+'.');}
      const c=this.repo.get(target);requireRule(c.kind==='container'&&c.location===loc.id,'Choose a stillage in this yard, the loading zone or the gate.');return {x:c.x-2200,y:c.y};}
    const obstacles=this.jobObstacles(loc);
    if(target==='loading')return spot(loc.loading);if(target==='gate')return spot(loc.gate);
    const fixture=(loc.fixtures??[]).find(f=>f.id===target);let box=null,name='there';
    if(fixture){box=fixture;name=fixture.name;}else{const o=this.repo.get(target);requireRule(o.location===loc.id,'Choose something in this yard.');if(o.kind==='container'){box=rect(o);name=o.name;}else if(o.kind==='resource'&&o.type==='FORKLIFT'){const p=this.forkliftPosition(o);requireRule(p,'That forklift has no parking spot yet.');return {x:Math.round(p.x+700),y:Math.round(p.y+1400)};}else requireRule(false,'Choose a stillage, forklift, fixture, the loading zone or the gate.');}
    const s=this.standingSpot(box,loc,obstacles);requireRule(s,'No clear spot beside '+name+'.');return s;
  },
  // ---------- derivation ----------
  deriveJobs(yard){
    const cfg=this.jobsConfig(),step=cfg.stepMs??700,dur=f=>f*step,now=Date.now(),effects=cfg.jobEffects??{},on=e=>effects[e]!==false;
    const stored=this.containers().filter(c=>c.location===yard.id),byId=new Map(stored.map(c=>[c.id,c])),tasks=this.tasks().filter(active),resources=this.repo.all('resource').filter(r=>r.enabled);
    const busy=new Set();for(const t of tasks){busy.add(t.container);if(t.sourceContainer)busy.add(t.sourceContainer);if(t.position?.support)busy.add(t.position.support);}for(const r of resources){if(r.cargo)busy.add(r.cargo);if(r.drive?.container)busy.add(r.drive.container);}for(const c of stored)if(c.support)busy.add(c.support);
    const counts=this.repo.all('count').filter(n=>n.state==='OPEN'),locked=c=>counts.some(n=>n.scope===c.id||n.scope===yard.id);
    const usable=c=>!busy.has(c.id)&&!locked(c)&&c.condition==='SERVICEABLE'&&!c.support;
    const linesCache=new Map(),lines=c=>{if(!linesCache.has(c.id))linesCache.set(c.id,this.repo.lines(c.id));return linesCache.get(c.id);};
    const reservations=this.repo.all('reservation').filter(r=>r.active),reserved=(c,p)=>reservations.filter(r=>r.container===c&&r.product===p).reduce((s,r)=>s+r.quantity,0);
    const products=new Map(this.effectiveProducts().map(p=>[p.id,p]));const obstacles=this.jobObstacles(yard);const beside=c=>this.standingSpot(rect(c),yard,obstacles);
    const level=c=>{let n=1,cur=c,g=0;while(cur?.support&&g++<9){n++;cur=byId.get(cur.support);}return n;};
    const out=[];const add=(key,priority,category,effect,title,extra={})=>{const cand={key,priority,category,effect,title,badge:badgeOf(effect),hazard:false,detail:null,subject:null,params:{},target:null,durationMs:dur(3),blocked:null,...extra};if(cand.blocked===null&&cand.target===undefined)cand.target=null;out.push(cand);};
    const blockedSpot=(cand)=>{if(cand.target){cand.target={x:Math.round(cand.target.x),y:Math.round(cand.target.y)};if(!cand.blocked&&!this.spotClear(cand.target,yard,obstacles))cand.blocked='No clear spot for a worker';}else if(cand.needsSpot&&!cand.blocked)cand.blocked='No clear spot beside it for a worker';delete cand.needsSpot;return cand;};
    const trucks=this.repo.all('truck').filter(t=>!t.retired&&t.yard===yard.id);const lists=this.loadLists();
    // P1 unload of a truck that came home with returns (an instant engine trigger, recorded as done)
    if(on('UNLOAD'))for(const t of trucks.filter(t=>t.status==='AT_YARD'&&t.at===yard.id&&t.delivery)){let d=null;try{d=this.repo.get(t.delivery,'delivery');}catch{}if(!d||d.status!=='ARRIVED'||d.to!==yard.id||t.autoUnloadDeclined===d.id)continue;if(!this.containers().some(c=>c.location===t.id)||tasks.some(x=>x.from===t.id))continue;add('P1:UNLOAD:'+t.id+':'+d.id,1,'TRUCK','UNLOAD','Unload returns from '+t.name,{params:{truck:t.id,delivery:d.id},subject:{kind:'truck',id:t.id,name:t.name},durationMs:0,trigger:true});}
    // P1 load check: a loaded yard list waiting to leave
    for(const l of lists){if(l.status!=='LOADED'||!l.truck)continue;const t=trucks.find(t=>t.id===l.truck);if(!t||t.status!=='AT_YARD'||t.at!==yard.id||tasks.some(x=>x.to===t.id||x.from===t.id))continue;const deck=this.containers().filter(c=>c.location===t.id);const newest=deck.reduce((m,c)=>c.placedAt&&c.placedAt>m?c.placedAt:m,'');if(l.checked?.at&&l.checked.at>=newest)continue;add('P1:LOAD_CHECK:'+l.id+':'+newest,1,'TRUCK','LOAD_CHECK','Check load against yard list – '+t.name+' – '+l.name,{params:{loadList:l.id,truck:t.id},subject:{kind:'truck',id:t.id,name:t.name},target:spot(yard.loading),detail:l.requested+' pieces on the list'});}
    // P1 hazards: tall piles not checked lately, movements blocked for want of a route
    for(const c of stored){if(stored.some(o=>o.support===c.id))continue;const lv=level(c);if(lv<5)continue;if(c.stackCheckedAt&&now-Date.parse(c.stackCheckedAt)<(cfg.checkCycleMs??1800000))continue;let base=c,g=0;while(base.support&&g++<9)base=byId.get(base.support)??base;add('P1:STACK_CHECK:'+c.id,1,'SAFETY','STACK_CHECK','Check stability – pile at '+base.name+' ('+lv+' high)',{hazard:true,params:{container:c.id},subject:{kind:'container',id:c.id,name:c.name},target:beside(base),needsSpot:true,durationMs:dur(2)});}
    for(const t of tasks.filter(t=>t.state==='BLOCKED'&&t.handling===yard.id&&!t.routeReviewed&&/No clear path|route/i.test(t.reason??''))){const c=byId.get(t.container);add('P1:ROUTE_CLEAR:'+t.id,1,'SAFETY','ROUTE_CLEAR','Clear a forklift route for '+(c?.name??'the blocked move'),{hazard:true,params:{task:t.id},subject:{kind:'task',id:t.id,name:c?.name??'movement'},target:c?beside(c):null,durationMs:dur(4),detail:t.reason});}
    // P2 / P3 yard lists: a truck booked = load required today; no truck yet = tomorrow's load
    for(const l of lists){if(l.cancelled)continue;if(l.status==='RESERVED'&&l.truck&&!l.labelled)add('P2:LABEL:'+l.id,2,'ORDERS','LABEL','Label picked packs – '+l.name,{params:{loadList:l.id},subject:{kind:'loadList',id:l.id,name:l.name},target:spot(yard.loading),durationMs:dur(2)});if(l.status==='OPEN'&&!l.truck&&!l.prechecked)add('P3:PRECHECK:'+l.id,3,'ORDERS','PRECHECK','Pre-check stock for '+l.name+' – '+l.lines.length+' line'+(l.lines.length===1?'':'s'),{params:{loadList:l.id},subject:{kind:'loadList',id:l.id,name:l.name},durationMs:dur(2)});}
    // P4 returned material, P8 clean it once checked
    for(const c of stored){if(!c.delivery||busy.has(c.id)||locked(c))continue;let d=null;try{d=this.repo.get(c.delivery,'delivery');}catch{}if(!d)continue;let from=null;try{from=this.repo.get(d.from);}catch{}if(from?.kind!=='site')continue;const held=lines(c);const detail=held.length?held.map(l=>l.quantity+' × '+(products.get(l.product_id)?.name??'material')).join(', ')+' – count, condition, strip tags':'returned empty – ready for reuse';
      if(c.returnChecked!==c.delivery)add('P4:RETURN_CHECK:'+c.id+':'+d.id,4,'RETURNS','RETURN_CHECK','Check returns '+c.name+' from '+from.name,{params:{container:c.id,delivery:d.id},subject:{kind:'container',id:c.id,name:c.name},target:beside(c),needsSpot:true,detail,durationMs:dur(4)+held.reduce((s,l)=>s+l.quantity,0)*Math.floor(step/14)});
      else if(held.length&&c.cleaned!==c.delivery)add('P8:CLEAN:'+c.id+':'+d.id,8,'MAINTENANCE','CLEAN','Clean & de-tag returned '+c.name,{params:{container:c.id,delivery:d.id},subject:{kind:'container',id:c.id,name:c.name},target:beside(c),needsSpot:true,durationMs:dur(5)});}
    // P5 consolidate partial stillages of one product, sort mixed stillages
    const single=stored.filter(c=>c.type==='STILLAGE'&&usable(c)&&lines(c).length===1&&!stored.some(o=>o.support===c.id));
    const room=(c,p)=>{const held=this.repo.quantity(c.id,p.id);let r=p.packQuantity!==null?p.packQuantity-held:Infinity;if(c.capacity!==null&&p.unitWeight!==null){let w=null;try{w=this.weight(c);}catch{return 0;}r=Math.min(r,Math.floor((c.capacity-w)/p.unitWeight));}return Math.max(0,r);};
    if(on('CONSOLIDATE'))for(const p of products.values()){if(p.packQuantity===null||p.retired)continue;const partial=single.filter(c=>{const l=lines(c)[0];return l.product_id===p.id&&l.quantity<p.packQuantity;}).sort((a,b)=>lines(b)[0].quantity-lines(a)[0].quantity);if(partial.length<2)continue;const to=partial[0],from=partial.slice(1).find(c=>dist(c,to)<=8000);if(!from)continue;const q=Math.min(lines(from)[0].quantity-reserved(from.id,p.id),room(to,p));if(q<=0)continue;add('P5:CONSOLIDATE:'+p.id+':'+from.id+':'+to.id,5,'HANDLING','CONSOLIDATE','Consolidate '+p.name+' – '+from.name+' ('+lines(from)[0].quantity+') → '+to.name+' ('+lines(to)[0].quantity+'/'+p.packQuantity+')',{params:{product:p.id,from:from.id,to:to.id,quantity:q},subject:{kind:'container',id:from.id,name:from.name},target:beside(from),needsSpot:true,durationMs:dur(6)+q*Math.floor(step/35)});}
    if(on('SORT'))for(const c of stored.filter(c=>c.type==='STILLAGE'&&usable(c)&&lines(c).length>1&&!stored.some(o=>o.support===c.id))){const smallest=[...lines(c)].sort((a,b)=>a.quantity-b.quantity)[0],p=products.get(smallest.product_id);if(!p)continue;const q=smallest.quantity-reserved(c.id,p.id);if(q<=0)continue;const empty=stored.find(o=>o.id!==c.id&&o.type==='STILLAGE'&&usable(o)&&!lines(o).length&&!stored.some(x=>x.support===o.id)&&dist(o,c)<=8000&&room(o,p)>0),partial=empty??single.find(o=>o.id!==c.id&&lines(o)[0].product_id===p.id&&room(o,p)>0&&dist(o,c)<=8000);const to=empty??partial;add('P5:SORT:'+c.id,5,'HANDLING','SORT','Sort mixed '+c.name+' – move '+q+' × '+p.name+(to?' into '+to.name+(empty?' (empty)':''):''),{params:{product:p.id,from:c.id,to:to?.id??null,quantity:to?Math.min(q,room(to,p)):q},subject:{kind:'container',id:c.id,name:c.name},target:beside(c),needsSpot:true,durationMs:dur(8),blocked:to?null:'Needs a serviceable stillage with room within 8 m'});}
    // P6 cycle counts due (the three longest waiting); never opens a stocktake by itself
    const cycle=cfg.countCycleMs??900000;const due=stored.filter(c=>lines(c).length&&!locked(c)&&!busy.has(c.id)&&(!c.countedAt||now-Date.parse(c.countedAt)>=cycle)).sort((a,b)=>(a.countedAt??'')<(b.countedAt??'')?-1:1).slice(0,3);
    for(const c of due)add('P6:COUNT:'+c.id,6,'STOCK','COUNT','Cycle count due – '+c.name+' ('+lines(c).map(l=>l.quantity+' × '+(products.get(l.product_id)?.name??'material')).join(', ')+' on system)',{params:{container:c.id},subject:{kind:'container',id:c.id,name:c.name},target:beside(c),needsSpot:true,durationMs:dur(4)});
    // P7 forklift pre-start checks, stacking loose empties
    for(const m of resources.filter(r=>r.type==='FORKLIFT'&&r.location===yard.id&&!r.task&&!r.driver&&!r.claimedBy&&!r.cargo&&!r.drive&&Number.isFinite(r.x))){if(m.checkedAt&&now-Date.parse(m.checkedAt)<(cfg.checkCycleMs??1800000))continue;add('P7:PRESTART:'+m.id,7,'EQUIPMENT','PRESTART','Pre-start check due – '+m.name,{params:{forklift:m.id},subject:{kind:'forklift',id:m.id,name:m.name},target:{x:m.x+700,y:m.y+1400},durationMs:dur(3)});}
    if(on('STACK')){const loose=stored.filter(c=>c.type==='STILLAGE'&&usable(c)&&!lines(c).length&&!stored.some(o=>o.support===c.id));if(loose.length>=4){const top=[...loose].sort((a,b)=>b.name.localeCompare(a.name,undefined,{numeric:true}))[0];const base=loose.filter(c=>c.id!==top.id).sort((a,b)=>dist(a,top)-dist(b,top))[0];let ok=false;try{this.validatePlacement(top,yard.id,{x:base.x,y:base.y,rotation:base.rotation,support:base.id});ok=true;}catch{}if(ok)add('P7:STACK:'+top.id+':'+base.id,7,'YARD','STACK','Stack empty '+top.name+' onto '+base.name,{params:{top:top.id,base:base.id},subject:{kind:'container',id:top.id,name:top.name},target:beside(top),needsSpot:true,durationMs:dur(1)});}}
    // P8 sweep the loading zone after the latest run
    const last=this.repo.all('delivery').filter(d=>['DELIVERED','RETURNED'].includes(d.status)&&(d.to===yard.id||d.from===yard.id)).at(-1);if(last&&yard.lastSweep!==last.id){let tn='the last run';try{tn=this.repo.get(last.truck,'truck').name;}catch{}add('P8:SWEEP:'+last.id,8,'YARD','SWEEP','Sweep loading zone after '+tn,{params:{delivery:last.id},subject:{kind:'zone',id:yard.id,name:'Loading zone'},target:spot(yard.loading),durationMs:dur(3)});}
    return out.map(blockedSpot);
  },
  // ---------- tick phases ----------
  jobPhase(yard,name,fn){this.db.exec('SAVEPOINT jobs_'+name);try{fn();this.db.exec('RELEASE jobs_'+name);faults.set(yard.id+':'+name,0);}catch(error){this.db.exec('ROLLBACK TO jobs_'+name);this.db.exec('RELEASE jobs_'+name);console.error(JSON.stringify({event:'jobs_error',phase:name,yard:yard.id,message:error.message}));const n=(faults.get(yard.id+':'+name)??0)+1;faults.set(yard.id+':'+name,n);if(n>=3){const c=this.repo.all('config')[0];if(c&&!c.jobsFault){c.jobsFault={at:ISO(),message:error.status?error.message:'Yard jobs stopped after repeated errors. Review the server log.'};this.repo.save(c);this.notify('Yard jobs paused',c.jobsFault.message,null);}}}},
  tickJobs(elapsed){const cfg=this.jobsConfig();for(const yard of this.repo.all('yard')){this.jobPhase(yard,'advance',()=>this.advanceJobs(yard,elapsed));if(cfg.jobs===false||cfg.jobsFault)continue;const clock=clocks.get(yard.id)??{accumulatedMs:Infinity};clock.accumulatedMs=(clock.accumulatedMs===Infinity?Infinity:clock.accumulatedMs+elapsed);clocks.set(yard.id,clock);if(clock.accumulatedMs>=(cfg.jobRefreshMs??1000)){clock.accumulatedMs=0;this.jobPhase(yard,'refresh',()=>this.refreshJobs(yard));}this.jobPhase(yard,'assign',()=>this.assignJobs(yard));}},
  refreshJobs(yard){
    const now=ISO(),live=this.liveJobs(yard.id),derived=this.deriveJobs(yard),keys=new Set(derived.map(c=>c.key));
    for(const cand of derived){const existing=live.find(j=>j.key===cand.key);
      if(cand.trigger){if(existing&&existing.state!=='BLOCKED')continue;try{const tasks=this.unload({id:cand.params.truck});for(const t of tasks){t.actor='engine:'+yard.id;this.repo.save(t);}const rec={yard:yard.id,key:cand.key,origin:'DERIVED',priority:1,category:'TRUCK',hazard:false,title:cand.title,detail:null,subject:cand.subject,effect:'UNLOAD',badge:'REAL',params:cand.params,target:null,durationMs:0,remainingMs:0,state:'DONE',worker:null,assignedBy:'AUTO',blocked:null,reason:null,cooldownMs:0,failures:0,result:tasks.length+' unload move'+(tasks.length===1?'':'s')+' queued for the forklift',actor:'engine:'+yard.id,createdAt:now,startedAt:now,completedAt:now};if(existing)this.repo.save({...existing,...rec,id:existing.id,kind:existing.kind,version:existing.version});else this.repo.add('job',rec);}catch(error){if(!error.status)throw error;const rec={yard:yard.id,key:cand.key,origin:'DERIVED',priority:1,category:'TRUCK',hazard:false,title:cand.title,detail:null,subject:cand.subject,effect:'UNLOAD',badge:'REAL',params:cand.params,target:null,durationMs:0,remainingMs:0,state:'BLOCKED',worker:null,assignedBy:null,blocked:error.message,reason:null,cooldownMs:0,failures:0,result:null,actor:'engine:'+yard.id,createdAt:now,startedAt:null,completedAt:null};if(existing)this.repo.save({...existing,blocked:error.message,title:cand.title});else this.repo.add('job',rec);}continue;}
      if(!existing){this.repo.add('job',{yard:yard.id,key:cand.key,origin:'DERIVED',priority:cand.priority,category:cand.category,hazard:cand.hazard,title:cand.title,detail:cand.detail,subject:cand.subject,effect:cand.effect,badge:cand.badge,params:cand.params,target:cand.target,durationMs:cand.durationMs,remainingMs:cand.durationMs,state:cand.blocked?'BLOCKED':'OPEN',worker:null,assignedBy:null,blocked:cand.blocked,reason:null,cooldownMs:0,failures:0,result:null,actor:'engine:'+yard.id,createdAt:now,startedAt:null,completedAt:null});continue;}
      if(!['OPEN','BLOCKED'].includes(existing.state))continue;
      const before=JSON.stringify([existing.title,existing.detail,existing.params,existing.target,existing.state,existing.blocked]);existing.title=cand.title;existing.detail=cand.detail;existing.params=cand.params;if(cand.target)existing.target=cand.target;
      if(cand.blocked){existing.state='BLOCKED';existing.blocked=cand.blocked;}else if(existing.state==='BLOCKED'&&(existing.failures===0||Date.now()-Date.parse(existing.failedAt??existing.createdAt)>=30000)){existing.state='OPEN';existing.blocked=null;existing.failures=0;existing.cooldownMs=0;}
      if(JSON.stringify([existing.title,existing.detail,existing.params,existing.target,existing.state,existing.blocked])!==before)this.repo.save(existing);}
    for(const j of live){if(j.origin!=='DERIVED'||keys.has(j.key))continue;if(['ASSIGNED','IN_PROGRESS'].includes(j.state)&&j.effect!=='UNLOAD')continue;if(j.worker){const w=this.repo.get(j.worker,'resource');this.releaseJob(w,'No longer needed');this.repo.save(w);}const fresh=this.repo.get(j.id,'job');fresh.state='EXPIRED';fresh.completedAt=now;this.repo.save(fresh);}
    const closed=this.repo.all('job').filter(j=>j.yard===yard.id&&!LIVE.includes(j.state)),routine=closed.filter(j=>j.origin==='ROUTINE'),real=closed.filter(j=>j.origin!=='ROUTINE');const byDone=(a,b)=>(a.completedAt??'').localeCompare(b.completedAt??'');routine.sort(byDone);real.sort(byDone);for(const j of [...routine.slice(0,Math.max(0,routine.length-10)),...real.slice(0,Math.max(0,real.length-100))])this.repo.remove(j.id,'job');
  },
  assignJobs(yard){
    const cfg=this.jobsConfig(),now=Date.now(),stamp=ISO();
    let free=this.repo.all('resource').filter(r=>r.enabled&&r.type==='WORKER'&&r.location===yard.id&&Number.isFinite(r.x)&&Number.isFinite(r.y)&&!r.task&&!r.walk&&!r.mountedOn&&!r.mountTarget&&!r.job&&(!r.workerMode||r.workerMode==='AUTO')&&!(r.assignHoldUntil&&Date.parse(r.assignHoldUntil)>now)&&!(r.jobSkipUntil&&Date.parse(r.jobSkipUntil)>now));
    if(!free.length)return;const obstacles=this.jobObstacles(yard);let routes=0;
    // A worker a stillage was set down on cannot route anywhere: re-seat them on clear ground first.
    free=free.filter(w=>{if(!this.reseatIfStuck(w,obstacles))return true;this.repo.save(w);return Number.isFinite(w.x)&&Number.isFinite(w.y);});
    // Hold one skill-matched worker back for each forklift move that is already waiting for a worker.
    const waiting=this.tasks().filter(t=>active(t)&&t.handling===yard.id&&t.state!=='BLOCKED'&&!t.resources?.length&&/^Waiting for a worker/.test(t.reason??''));
    for(const skill of new Set(waiting.map(t=>this.taskInfo(t).skill))){const keep=free.find(w=>skillOn(w,skill));if(keep)free=free.filter(w=>w.id!==keep.id);}
    const walk=(w,target)=>{routes++;return route({x:w.x,y:w.y},target,{w:500,h:500},yard.points,obstacles,500);};
    const start=(job,w,path)=>{job.worker=w.id;job.assignedBy='AUTO';job.assignedAt=stamp;job.cooldownMs=0;job.blocked=null;w.job=job.id;w.workerReason=null;if(path){job.state='ASSIGNED';w.walk={path,next:1,job:job.id};}else{job.state='IN_PROGRESS';job.startedAt=stamp;}this.repo.save(job);this.repo.save(w);free=free.filter(x=>x.id!==w.id);};
    const open=this.liveJobs(yard.id).filter(j=>j.state==='OPEN'&&j.cooldownMs<=0&&j.effect!=='UNLOAD').sort((a,b)=>a.priority-b.priority||a.createdAt.localeCompare(b.createdAt));
    for(const job of open){if(!free.length)break;const w=free.filter(w=>skillOn(w,job.category)).sort((a,b)=>(job.target?dist(a,job.target)-dist(b,job.target):0))[0];if(!w)continue;
      if(!job.target||dist(w,job.target)<=1){start(job,w,null);continue;}
      if(routes>=4)break;const path=walk(w,job.target);if(path){start(job,w,path);continue;}
      // The spot cannot be reached from where the crew stands: cool the job down, and block it after three tries.
      job.failures=(job.failures??0)+1;job.failedAt=stamp;job.cooldownMs=5000;job.reason='No clear walking route to this job';if(job.failures>=3){job.state='BLOCKED';job.blocked='No clear walking route to this job';}this.repo.save(job);}
    if(cfg.routineJobs===false)return;
    const board=this.repo.all('jobBoard').find(b=>b.yard===yard.id)??{marks:{}},liveKeys=new Set(this.liveJobs(yard.id).map(j=>j.key));
    const nearestForklift=w=>{const m=this.repo.all('resource').filter(r=>r.enabled&&r.type==='FORKLIFT'&&r.location===yard.id&&Number.isFinite(r.x)).sort((a,b)=>dist(a,w)-dist(b,w))[0];return m?{x:Math.round(m.x+700),y:Math.round(m.y+1400)}:null;};
    for(const w of [...free]){if(w.dwellUntil&&Date.parse(w.dwellUntil)>now)continue;const v=this.routineVerbs(w,board,liveKeys)[0];if(!v)continue;
      let target=v.category==='YARD'||v.category==='SAFETY'?spot(yard.gate):v.category==='EQUIPMENT'?nearestForklift(w):null,path=null;
      // Routine work is done where the worker stands when its usual spot is blocked, unreachable or over this tick's routing budget.
      if(target&&(!this.spotClear(target,yard,obstacles)||routes>=4||dist(w,target)<=1))target=null;if(target){path=walk(w,target);if(!path)target=null;}
      const job=this.routineJob(yard,v,target,stamp);liveKeys.add(job.key);start(job,w,path);}
  },
  routineVerbs(w,board,liveKeys){return SKILLS.filter(s=>s.routine&&skillOn(w,s.code)).flatMap(s=>s.vocabulary.map(v=>({verb:v,category:s.code,priority:s.priority,done:board.marks['ROUTINE:'+v]??''}))).filter(x=>!liveKeys.has('ROUTINE:'+x.verb)).sort((a,b)=>a.done.localeCompare(b.done)||a.priority-b.priority);},
  routineJob(yard,v,target,stamp){const d=(this.jobsConfig().stepMs??700)*(4+(v.verb.length%5));return this.repo.add('job',{yard:yard.id,key:'ROUTINE:'+v.verb,origin:'ROUTINE',priority:v.priority,category:v.category,hazard:false,title:v.verb,detail:'Routine work between jobs (demo timer)',subject:null,effect:'RECORD',badge:'RECORDED',params:{},target,durationMs:d,remainingMs:d,state:'OPEN',worker:null,assignedBy:null,blocked:null,reason:null,cooldownMs:0,failures:0,result:null,actor:'engine:'+yard.id,createdAt:stamp,startedAt:null,completedAt:null});},
  spotClear(p,yard,obstacles){const r={x:p.x,y:p.y,w:500,h:500};return fitsPolygon(r,yard.points)&&!(obstacles??this.jobObstacles(yard)).some(o=>overlap(r,o));},
  // A stillage can be set down where a worker stands (placement does not treat crew as obstacles); such a worker is moved to clear ground.
  reseatIfStuck(w,obstacles){if(!Number.isFinite(w.x)||!Number.isFinite(w.y))return false;const loc=this.repo.get(w.location);const r={x:w.x,y:w.y,w:500,h:500};if(fitsPolygon(r,loc.points)&&!(obstacles??this.workerObstacles(loc.id)).some(o=>overlap(r,o)))return false;w.x=null;w.y=null;const p=this.workerPosition(w);if(p)Object.assign(w,p);w.workerReason=null;return true;},
  advanceJobs(yard,elapsed){
    const stamp=ISO();
    for(const job of this.liveJobs(yard.id)){
      if(job.cooldownMs>0){job.cooldownMs=Math.max(0,job.cooldownMs-elapsed);this.repo.save(job);}
      if(!['ASSIGNED','IN_PROGRESS'].includes(job.state))continue;
      let w=null;try{w=this.repo.get(job.worker,'resource');}catch{}
      if(!w||!w.enabled||w.location!==yard.id||w.job!==job.id){this.releaseJob(null,'Worker unavailable',0,job);if(w&&w.job===job.id){w.job=null;this.repo.save(w);}continue;}
      if(w.task){this.releaseJob(w,'Needed for '+this.taskInfo(this.repo.get(w.task,'task')).title);this.repo.save(w);continue;}
      if(job.state==='ASSIGNED'){if(!w.walk||w.walk.job!==job.id){this.releaseJob(w,'Walk interrupted',5000);this.repo.save(w);}continue;}
      job.remainingMs=Math.max(0,job.remainingMs-elapsed);if(job.remainingMs>0){this.repo.save(job);continue;}
      this.db.exec('SAVEPOINT job_step');
      try{const cfg=this.jobsConfig();requireRule(!(cfg.jobEffects?.[job.effect]===false),'This job type is switched off.');const result=EFFECTS[job.effect].call(this,job,w,yard);const fresh=this.repo.get(job.id,'job');fresh.state='DONE';fresh.result=result;fresh.completedAt=stamp;fresh.failures=0;fresh.remainingMs=0;this.repo.save(fresh);const fw=this.repo.get(w.id,'resource');fw.job=null;fw.workerReason=null;this.repo.save(fw);if(fresh.origin==='ROUTINE'){const board=this.jobBoard(yard);board.marks[fresh.key]=stamp;this.repo.save(board);}this.db.exec('RELEASE job_step');}
      catch(error){this.db.exec('ROLLBACK TO job_step');this.db.exec('RELEASE job_step');const fresh=this.repo.get(job.id,'job'),fw=this.repo.get(w.id,'resource');fresh.worker=null;fresh.assignedBy=null;fresh.remainingMs=fresh.durationMs;fresh.reason=error.status?error.message:'Job could not be completed safely. Review the server log.';fresh.cooldownMs=5000;fresh.failedAt=stamp;fresh.failures=(fresh.failures??0)+1;fresh.state=fresh.origin==='ROUTINE'?'EXPIRED':fresh.failures>=3?'BLOCKED':'OPEN';if(fresh.state==='BLOCKED')fresh.blocked=fresh.reason;if(fresh.state==='EXPIRED')fresh.completedAt=stamp;this.repo.save(fresh);fw.job=null;this.repo.save(fw);if(!error.status)console.error(JSON.stringify({event:'job_error',job:job.id,message:error.message}));}
    }
  },
  releaseJob(worker,reason,cooldown=0,job=null){const j=job??(worker?.job?(()=>{try{return this.repo.get(worker.job,'job');}catch{return null;}})():null);if(j&&['ASSIGNED','IN_PROGRESS'].includes(j.state)){j.state=j.origin==='ROUTINE'?'EXPIRED':'OPEN';j.worker=null;j.assignedBy=null;j.reason=reason;j.cooldownMs=cooldown;if(j.state==='EXPIRED')j.completedAt=ISO();this.repo.save(j);}if(worker){worker.job=null;if(worker.walk?.job)worker.walk=null;}return j;},
  jobBoard(yard){let b=this.repo.all('jobBoard').find(x=>x.yard===yard.id);if(!b)b=this.repo.add('jobBoard',{yard:yard.id,marks:{}});return b;},
  // ---------- snapshot helpers ----------
  jobsView(yardIds){const workers=new Map(this.repo.all('resource').map(r=>[r.id,r.name]));const view=j=>({...j,workerName:j.worker?workers.get(j.worker)??null:null,progress:j.state==='IN_PROGRESS'&&j.durationMs>0?Math.min(100,Math.round(100*(1-j.remainingMs/j.durationMs))):j.state==='DONE'?100:0,cooldownSeconds:Math.ceil((j.cooldownMs??0)/1000),remainingMs:undefined,version:undefined,cooldownMs:undefined});const all=this.repo.all('job').filter(j=>yardIds.has(j.yard));return {jobs:all.filter(j=>LIVE.includes(j.state)).sort((a,b)=>a.priority-b.priority||a.createdAt.localeCompare(b.createdAt)).slice(0,200).map(view),recentJobs:all.filter(j=>!LIVE.includes(j.state)&&j.origin!=='ROUTINE'&&j.state!=='EXPIRED').slice(-20).map(view)};},
  ladderView(yard,jobs,tasks){return LADDER.map(l=>{const js=jobs.filter(j=>j.yard===yard.id&&j.priority===l.priority&&j.origin!=='ROUTINE'),ts=tasks.filter(t=>t.handling===yard.id&&t.priority===l.priority);return {priority:l.priority,label:l.label,open:js.filter(j=>['OPEN','BLOCKED'].includes(j.state)).length+ts.filter(t=>!t.resources?.length).length,working:js.filter(j=>['ASSIGNED','IN_PROGRESS'].includes(j.state)).length+ts.filter(t=>t.resources?.length).length,blocked:js.filter(j=>j.state==='BLOCKED').length+ts.filter(t=>t.state==='BLOCKED').length};});},
  // NOW / NEXT / THEN / IDLE lines per worker: a distance-only dry run of the assigner, never routed, labelled "likely" in the UI.
  workerBoards(yard,workers,jobs,tasks){const now=Date.now(),board=this.repo.all('jobBoard').find(b=>b.yard===yard.id)??{marks:{}};const open=jobs.filter(j=>j.yard===yard.id&&j.state==='OPEN'&&j.effect!=='UNLOAD').sort((a,b)=>a.priority-b.priority||a.createdAt.localeCompare(b.createdAt));const out=new Map();const byTask=new Map(tasks.map(t=>[t.id,t]));const taken=new Set();
    const nowLine=w=>{if(w.task){const t=byTask.get(w.task);return {title:t?'P'+t.priority+' '+t.title:'On a forklift move',badge:'FORKLIFT',progress:null};}if(w.job){const j=jobs.find(x=>x.id===w.job);if(j)return {title:(j.state==='ASSIGNED'?'Walking to: ':'')+j.title,badge:j.origin==='ROUTINE'?'ROUTINE':j.hazard?'HAZARD':j.badge,progress:j.state==='IN_PROGRESS'?j.progress:null,job:j.id};}if(w.mountedOn)return {title:'Driving '+(this.repo.get(w.mountedOn,'resource').name),badge:null,progress:null};if(w.mountTarget)return {title:'Walking to the forklift',badge:null,progress:null};if(w.walk)return {title:'Walking on orders',badge:null,progress:null};if(w.workerMode==='HOLD')return {title:'Holding position',badge:null,progress:null};if(w.assignHoldUntil&&Date.parse(w.assignHoldUntil)>now)return {title:'Standing by – press Automatic or Allocate',badge:null,progress:null};return {title:'Standing by',badge:null,progress:null};};
    const rounds=[new Map(),new Map()];for(const round of rounds){for(const j of open){if(taken.has(j.id))continue;const cand=workers.filter(w=>skillOn(w,j.category)&&!round.has(w.id)&&(!w.workerMode||w.workerMode==='AUTO')&&!w.mountedOn).sort((a,b)=>(j.target&&Number.isFinite(a.x)&&Number.isFinite(b.x)?dist(a,j.target)-dist(b,j.target):0))[0];if(cand){round.set(cand.id,j);taken.add(j.id);}}}
    for(const w of workers){const rest=open.filter(j=>!taken.has(j.id)&&skillOn(w,j.category)).slice(0,3).map(j=>({title:'P'+j.priority+' '+j.title,id:j.id}));const routine=rest.length?[]:SKILLS.filter(s=>s.routine&&skillOn(w,s.code)).flatMap(s=>s.vocabulary.map(v=>({title:v,done:board.marks['ROUTINE:'+v]??''}))).sort((a,b)=>a.done.localeCompare(b.done)).slice(0,3).map(x=>({title:'Routine: '+x.title}));out.set(w.id,{now:nowLine(w),next:rounds[0].get(w.id)?{title:'P'+rounds[0].get(w.id).priority+' '+rounds[0].get(w.id).title,id:rounds[0].get(w.id).id}:null,then:rounds[1].get(w.id)?{title:'P'+rounds[1].get(w.id).priority+' '+rounds[1].get(w.id).title,id:rounds[1].get(w.id).id}:null,idle:rest.length?rest:routine});}
    return out;},
  // ---------- commands ----------
  workerSkills(input){const w=this.repo.get(input.id,'resource');requireRule(w.enabled&&w.type==='WORKER','Choose an enabled worker.');requireRule(input.skills&&typeof input.skills==='object'&&!Array.isArray(input.skills),'Choose valid skills.');const skills={...(w.skills??{})};for(const [code,on] of Object.entries(input.skills)){requireRule(SKILL[code]&&typeof on==='boolean','Choose valid skills.');if(on)delete skills[code];else skills[code]=false;}w.skills=skills;this.repo.save(w);return {...w,skills:this.normalisedSkills(w)};},
  createJob(input){const yard=this.repo.get(input.yard,'yard');const s=SKILL[input.category];requireRule(s,'Choose a job category.');const title=label(input.title,'Job title');requireRule(title.length<=120,'Job title is required (maximum 120 characters).');const priority=input.priority===undefined?s.priority:integer(input.priority,'Priority',1,8),seconds=input.seconds===undefined?20:integer(input.seconds,'Duration in seconds',1,600);
    const where=input.where??{kind:'here'};let target=null;if(where.kind==='loading'||where.kind==='gate'){target=spot(where.kind==='loading'?yard.loading:yard.gate);requireRule(this.spotClear(target,yard),'The '+(where.kind==='loading'?'loading zone':'gate')+' spot is blocked. Choose another place.');}else if(where.kind==='point'){const r={x:integer(where.x,'X',-1000000),y:integer(where.y,'Y',-1000000),w:500,h:500};requireRule(fitsPolygon(r,yard.points)&&!this.jobObstacles(yard).some(o=>overlap(r,o)),'Choose open ground inside the yard that a worker can reach.');target={x:r.x,y:r.y};}else if(['container','forklift','fixture'].includes(where.kind)){const probe={location:yard.id,mountedOn:null};target=this.resolveTarget(probe,where.id);}else requireRule(where.kind==='here','Choose where the job is done.');
    const job=this.repo.add('job',{yard:yard.id,key:'MANUAL:'+Math.random().toString(36).slice(2),origin:'MANUAL',priority,category:s.code,hazard:false,title,detail:input.detail?label(input.detail,'Detail'):null,subject:null,effect:'RECORD',badge:'RECORDED',params:{},target,durationMs:seconds*1000,remainingMs:seconds*1000,state:'OPEN',worker:null,assignedBy:null,blocked:null,reason:null,cooldownMs:0,failures:0,result:null,actor:this.user.id,createdAt:ISO(),startedAt:null,completedAt:null});job.key='MANUAL:'+job.id;this.repo.save(job);
    if(input.worker)return this.assignJob({id:job.id,worker:input.worker,resume:input.resume});return job;},
  assignJob(input){const job=this.repo.get(input.id,'job');requireRule(['OPEN','BLOCKED'].includes(job.state),'This job is not open.');requireRule(job.state!=='BLOCKED'||job.failures>0,job.blocked??'This job is blocked.');const w=this.repo.get(input.worker,'resource');requireRule(w.enabled&&w.type==='WORKER'&&w.location===job.yard,'Choose an enabled worker at this yard.');requireRule(!w.task,'This worker is assigned to a material movement. Finish that task first.');requireRule(!w.mountedOn,'Unmount first.');requireRule(!w.mountTarget,'Stop the walk to the forklift first.');requireRule(skillOn(w,job.category),'Turn on the '+SKILL[job.category].label+' skill for this worker first.');
    if(w.job)this.releaseJob(w,'Reassigned from the yard office');if(w.walk){const resume=input.resume===true||w.walk.resume===true;w.walk=null;w.workerMode=resume?'AUTO':'HOLD';}w.assignHoldUntil=null;w.jobSkipUntil=null;w.workerReason=null;this.reseatIfStuck(w,this.jobObstacles(this.repo.get(job.yard,'yard')));const pos=this.workerPosition(w);requireRule(pos,'There is no clear space for this worker.');Object.assign(w,pos);
    const yard=this.repo.get(job.yard,'yard');job.failures=0;job.cooldownMs=0;job.blocked=null;job.worker=w.id;job.assignedBy=this.user.id;job.assignedAt=ISO();w.job=job.id;
    if(job.target&&dist(w,job.target)>1){const path=route({x:w.x,y:w.y},job.target,{w:500,h:500},yard.points,this.jobObstacles(yard),500);requireRule(path,'No clear walking route to this job.');job.state='ASSIGNED';w.walk={path,next:1,job:job.id};}else{job.state='IN_PROGRESS';job.startedAt=ISO();}
    this.repo.save(job);this.repo.save(w);return job;},
  nextJob(input){const cfg=this.jobsConfig();const give=w=>{const open=this.liveJobs(w.location).filter(j=>j.state==='OPEN'&&j.cooldownMs<=0&&j.effect!=='UNLOAD'&&skillOn(w,j.category)).sort((a,b)=>a.priority-b.priority||a.createdAt.localeCompare(b.createdAt));for(const j of open){try{return this.assignJob({id:j.id,worker:w.id,resume:input.resume});}catch(error){if(!error.status||!/route/.test(error.message))throw error;}}
      if(cfg.routineJobs===false)return null;const yard=this.repo.get(w.location,'yard'),board=this.jobBoard(yard),liveKeys=new Set(this.liveJobs(yard.id).map(j=>j.key));const v=this.routineVerbs(w,board,liveKeys)[0];if(!v)return null;const job=this.routineJob(yard,v,null,ISO());return this.assignJob({id:job.id,worker:w.id,resume:input.resume});};
    if(input.yard){const yard=this.repo.get(input.yard,'yard');let assigned=0;for(const w of this.repo.all('resource').filter(r=>r.enabled&&r.type==='WORKER'&&r.location===yard.id&&!r.task&&!r.job&&!r.mountedOn&&!r.mountTarget&&!r.walk&&r.workerMode!=='MOVING'))if(give(w))assigned++;return {assigned,message:assigned+' worker'+(assigned===1?'':'s')+' given a job.'};}
    const w=this.repo.get(input.id,'resource');requireRule(w.enabled&&w.type==='WORKER','Choose an enabled worker.');const job=give(w);requireRule(job,"Nothing on the board matches this worker's skills.");return job;},
  takeOffJob(input){const job=this.repo.get(input.id,'job');requireRule(['ASSIGNED','IN_PROGRESS'].includes(job.state),'This job is not assigned.');const w=this.repo.get(job.worker,'resource');this.releaseJob(w,'Taken off by the yard office',0,job);w.assignHoldUntil=new Date(Date.now()+10000).toISOString();this.repo.save(w);return this.repo.get(job.id,'job');},
  cancelJob(input){const job=this.repo.get(input.id,'job');requireRule(job.origin==='MANUAL','Derived jobs cannot be cancelled; they expire when the yard state changes.');requireRule(LIVE.includes(job.state),'This job is already closed.');const reason=label(input.reason??'Cancelled','Reason');if(job.worker){const w=this.repo.get(job.worker,'resource');this.releaseJob(w,reason,0,job);w.assignHoldUntil=new Date(Date.now()+10000).toISOString();this.repo.save(w);}const fresh=this.repo.get(job.id,'job');fresh.state='CANCELLED';fresh.reason=reason;fresh.completedAt=ISO();return this.repo.save(fresh);},
  jobsMode(input){const config=this.repo.all('config')[0];requireRule(config,'Configure yard resources first.');for(const k of ['jobs','routineJobs'])if(input[k]!==undefined){requireRule(typeof input[k]==='boolean','Choose on or off.');config[k]=input[k];}
    if(input.jobEffects!==undefined){requireRule(input.jobEffects&&typeof input.jobEffects==='object','Choose on or off.');const eff={...(config.jobEffects??{})};for(const [k,v] of Object.entries(input.jobEffects)){requireRule(['UNLOAD','CONSOLIDATE','SORT','STACK'].includes(k)&&typeof v==='boolean','Choose on or off.');if(v)delete eff[k];else eff[k]=false;}config.jobEffects=eff;}
    if(input.jobs===true){config.jobsFault=null;for(const k of [...faults.keys()])faults.set(k,0);}
    if(input.jobs===false||input.routineJobs===false)this.releaseAllJobs(input.jobs===false?null:'ROUTINE');
    return this.repo.save(config);},
  releaseAllJobs(originOnly){for(const w of this.repo.all('resource').filter(r=>r.enabled&&r.type==='WORKER'&&r.job)){let j=null;try{j=this.repo.get(w.job,'job');}catch{}if(originOnly&&j?.origin!==originOnly)continue;this.releaseJob(w,'Yard jobs switched off',0,j);if(!j)w.job=null;this.repo.save(w);}},
};
// Effects run when a job's timer ends; each re-checks its own preconditions and returns the result text.
const EFFECTS={
  RECORD(job,w){return job.origin==='ROUTINE'?null:'Done by '+w.name;},
  LOAD_CHECK(job,w){const list=this.loadListView(this.repo.get(job.params.loadList,'loadList'));const short=list.lines.filter(x=>x.loaded<x.quantity).map(x=>(x.quantity-x.loaded)+' × '+x.name);const raw=this.repo.get(list.id,'loadList');raw.checked={worker:w.id,workerName:w.name,at:ISO(),short};this.repo.save(raw);const result=short.length?'Short: '+short.join(', '):'Load matches the yard list';this.notify('Load checked',list.name+': '+result+' ('+w.name+')',list.site);return result;},
  LABEL(job,w){const raw=this.repo.get(job.params.loadList,'loadList');raw.labelled={worker:w.id,workerName:w.name,at:ISO()};this.repo.save(raw);return 'Labels recorded for '+raw.lines.length+' line'+(raw.lines.length===1?'':'s')+' (no label printed)';},
  PRECHECK(job,w){const raw=this.repo.get(job.params.loadList,'loadList'),view=this.loadListView(raw);const yardId=job.yard;const short=[];for(const line of view.lines){const product=this.effective(line.product);const free=this.containers().filter(c=>c.location===yardId&&c.condition==='SERVICEABLE'&&!c.support&&this.repo.lines(c.id).length===1&&this.repo.quantity(c.id,product.id)>0).reduce((s,c)=>s+this.repo.quantity(c.id,product.id)-this.repo.all('reservation').filter(r=>r.active&&r.container===c.id&&r.product===product.id).reduce((x,r)=>x+r.quantity,0),0);if(free<line.quantity)short.push({product:product.id,name:product.name,needed:line.quantity,free});}raw.prechecked={worker:w.id,workerName:w.name,at:ISO(),short};this.repo.save(raw);const result=short.length?'Short: '+short.map(s=>s.name+' '+s.needed+' needed, '+s.free+' free').join('; '):'Every line can be reserved';this.notify('Yard list pre-checked',raw.name+': '+result,raw.site);return result;},
  RETURN_CHECK(job,w){const c=this.repo.get(job.params.container,'container');requireRule(c.location===job.yard,'The stillage has moved.');this.assertCountFree(c);c.returnChecked=job.params.delivery;this.repo.save(c);return 'Returns check recorded – contents as per system; use Mark damaged or Start stocktake if they differ';},
  CLEAN(job,w){const c=this.repo.get(job.params.container,'container');requireRule(c.location===job.yard,'The stillage has moved.');c.cleaned=job.params.delivery;this.repo.save(c);return 'Cleaning recorded';},
  CONSOLIDATE(job,w,yard){const {product,from,to}=job.params;const a=this.repo.get(from,'container'),b=this.repo.get(to,'container'),p=this.effective(product);requireRule(a.location===yard.id&&b.location===yard.id,'A stillage has moved.');this.assertFree(a);this.assertFree(b);requireRule(a.condition==='SERVICEABLE'&&b.condition==='SERVICEABLE','Only serviceable stock is consolidated.');const held=this.repo.quantity(a.id,p.id),reserved=this.repo.all('reservation').filter(r=>r.active&&r.container===a.id&&r.product===p.id).reduce((s,r)=>s+r.quantity,0);let q=Math.min(job.params.quantity,held-reserved);if(p.packQuantity!==null)q=Math.min(q,p.packQuantity-this.repo.quantity(b.id,p.id));requireRule(q>0,'Nothing left to move.');this.repo.balance(a.id,p.id,-q);this.repo.balance(b.id,p.id,q);if(b.capacity!==null&&p.unitWeight!==null)requireRule(this.weight(b)<=b.capacity,'The target stillage would be over its capacity.');this.repo.event(job.actor,'CONSOLIDATED',{container:b.id,product:p.id,quantity:q,source:a.id,destination:b.id,reason:job.title+' – '+w.name,key:job.id+':done'});return q+' pieces moved into '+b.name+(this.repo.lines(a.id).length?'':'; '+a.name+' now empty');},
  SORT(job,w,yard){const {product,from,to}=job.params;requireRule(to,'Needs an empty serviceable stillage within 8 m');const a=this.repo.get(from,'container'),b=this.repo.get(to,'container'),p=this.effective(product);requireRule(a.location===yard.id&&b.location===yard.id,'A stillage has moved.');this.assertFree(a);this.assertFree(b);const held=this.repo.quantity(a.id,p.id),reserved=this.repo.all('reservation').filter(r=>r.active&&r.container===a.id&&r.product===p.id).reduce((s,r)=>s+r.quantity,0);let q=Math.min(job.params.quantity,held-reserved);if(p.packQuantity!==null)q=Math.min(q,p.packQuantity-this.repo.quantity(b.id,p.id));requireRule(q>0,'Nothing left to move.');const bl=this.repo.lines(b.id);requireRule(!bl.length||(bl.length===1&&bl[0].product_id===p.id),'The target stillage now holds something else.');this.repo.balance(a.id,p.id,-q);this.repo.balance(b.id,p.id,q);if(b.capacity!==null&&p.unitWeight!==null)requireRule(this.weight(b)<=b.capacity,'The target stillage would be over its capacity.');this.repo.event(job.actor,'SORTED',{container:b.id,product:p.id,quantity:q,source:a.id,destination:b.id,reason:job.title+' – '+w.name,key:job.id+':done'});return q+' × '+p.name+' moved into '+b.name;},
  COUNT(job,w){const c=this.repo.get(job.params.container,'container');requireRule(c.location===job.yard,'The stillage has moved.');c.countedAt=ISO();this.repo.save(c);return 'Count due recorded – open a stocktake to record observed quantities';},
  PRESTART(job,w){const m=this.repo.get(job.params.forklift,'resource');requireRule(m.enabled,'The forklift was removed.');m.checkedAt=ISO();this.repo.save(m);return 'Pre-start due recorded (no checklist captured)';},
  STACK(job,w,yard){const top=this.repo.get(job.params.top,'container'),base=this.repo.get(job.params.base,'container');requireRule(top.location===yard.id&&base.location===yard.id,'A stillage has moved.');requireRule(!this.repo.lines(top.id).length&&!this.repo.lines(base.id).length,'A stillage is no longer empty.');requireRule(top.condition==='SERVICEABLE'&&base.condition==='SERVICEABLE'&&!base.support&&!top.support,'A stillage is no longer loose.');this.assertFree(base);const task=this.queue({container:top.id,destination:yard.id,position:{x:base.x,y:base.y,rotation:base.rotation,support:base.id}});task.actor=job.actor;this.repo.save(task);return 'Forklift move queued: '+top.name+' onto '+base.name;},
  STACK_CHECK(job,w){const c=this.repo.get(job.params.container,'container');c.stackCheckedAt=ISO();this.repo.save(c);return 'Pile checked – no measurement captured (demo)';},
  ROUTE_CLEAR(job){const t=this.repo.get(job.params.task,'task');t.routeReviewed=true;this.repo.save(t);return 'Route reviewed – use Retry on the movement';},
  SWEEP(job,w,yard){const y=this.repo.get(yard.id,'yard');y.lastSweep=job.params.delivery;this.repo.save(y);return 'Sweep recorded';},
};
