import { integer,requireRule,rect,route } from './geometry.js';
import { label } from './catalogue.js';
import { active } from './inventory.js';
export const logisticsMethods={
  cancelRequest(input){const request=this.repo.get(input.id,'request');this.assertSite(request.site);requireRule(!request.loadList||input.fromList,'This request belongs to a yard list. Cancel the yard list instead.');requireRule(!['CANCELLED','DELIVERED','RETURNED'].includes(request.status),'This request is already closed.');const tasks=this.tasks().filter(t=>t.request===request.id&&active(t));requireRule(!tasks.some(t=>t.picked),'Finish placement of material currently on equipment before cancelling the remainder.');for(const task of tasks.reverse()){task.state='CANCELLED';this.repo.save(task);this.release(task);}request.status='CANCELLED';request.cancelledBy=this.user.id;request.reason=label(input.reason,'Cancellation reason');this.repo.save(request);this.notify('Request cancelled','Unstarted reservations released; already moved stock stays at its actual location.',request.site);return request;},
  site(input){const supervisor=input.supervisor||null;if(supervisor)requireRule(this.db.prepare('SELECT user_id FROM memberships WHERE company_id=? AND user_id=?').get(this.user.company_id,supervisor),'Supervisor must belong to this company.');return this.repo.add('site',{name:label(input.name),address:label(input.address??'Demonstration site'),supervisor,status:'ACTIVE',points:[{x:0,y:0},{x:20000,y:0},{x:20000,y:16000},{x:0,y:16000}],height:10000,loading:{x:1000,y:1000},gate:{x:1000,y:1000},mode:'DEMO ONLY'});},
  archive(input){const site=this.repo.get(input.id,'site');requireRule(!this.containers().some(c=>c.location===site.id),'Return all containers and stock before archiving.');requireRule(!this.tasks().some(t=>active(t)&&(t.from===site.id||t.to===site.id)),'Resolve the open site movements first.');requireRule(!this.repo.all('request').some(r=>r.site===site.id&&!['DELIVERED','CANCELLED','RETURNED'].includes(r.status)),'Resolve open requests before archiving.');requireRule(!this.repo.all('count').some(c=>c.scope===site.id&&c.state==='OPEN'),'Resolve the site stocktake first.');site.status='ARCHIVED';this.repo.save(site);this.repo.event(this.user.id,'SITE_ARCHIVED',{destination:site.id,key:this.key});return site;},
  truck(input){const yard=this.repo.get(input.yard,'yard');return this.repo.add('truck',{name:label(input.name),yard:yard.id,at:yard.id,status:'AT_YARD',length:integer(input.length??6000,'Deck length',1),width:integer(input.width??2050,'Deck width',1),payload:integer(input.payload??12500000,'Payload (g)',1),height:integer(input.height??3000,'Load height',1),stackLimit:integer(input.stackLimit??2,'Truck stack limit',1,2),destination:null,mode:'DEMO ONLY'});},
  resources(input){const loc=this.repo.get(input.location);requireRule(['yard','site'].includes(loc.kind),'Configure resources at a yard or site.');const workers=integer(input.workers,'Workers',0,500),machines=integer(input.machines,'Machines',0,20);const existing=this.repo.all('resource').filter(r=>r.location===loc.id);requireRule(!existing.some(r=>r.task||r.walk||r.driver||r.claimedBy||r.mountedOn),'Do not remove busy workers or machines.');for(const r of existing){r.enabled=false;this.repo.save(r);}for(let i=0;i<workers;i++)this.repo.add('resource',{name:`Worker ${i+1}`,type:'WORKER',location:loc.id,enabled:true,task:null});for(let i=0;i<machines;i++)this.repo.add('resource',{name:`${loc.kind==='site'?'Crane':'Forklift'} ${i+1}`,type:loc.kind==='site'?'CRANE':'FORKLIFT',location:loc.id,enabled:true,task:null,capacity:integer(input.capacity??1500000,'Machine capacity (g)',1),reach:integer(input.reach??10000,'Reach (mm)',1)});let config=this.repo.all('config')[0];const values={stepMs:integer(input.stepMs??700,'Demo step time (ms)',100,60000),speed:integer(input.speed??4000,'Demo travel speed (mm/s)',1,100000),craneWorkers:integer(input.craneWorkers??1,'Crane workers',1,10),paused:config?.paused??false,mode:'SIMULATION / DEMONSTRATION'};return config?this.repo.save({...config,...values}):this.repo.add('config',values);},
  positionFor(c,locId,extra=[]){const loc=this.repo.get(locId);const xs=loc.kind==='truck'?[0]:[3500],ys=loc.kind==='truck'?[0]:[1000];let lastError;for(const other of this.occupied(locId,c.id)){const r=rect(other);xs.push(r.x+r.w);ys.push(r.y+r.h);}for(const rotation of [0,90])for(const y of [...new Set(ys)].sort((a,b)=>a-b))for(const x of [...new Set(xs)].sort((a,b)=>a-b)){const p={x,y,rotation,support:null};try{this.validatePlacement(c,locId,p,extra);return p;}catch(e){if(/payload|unknown/.test(e.message))throw e;lastError=e;}}throw lastError??new Error('No destination space.');},
  queue(input){const c=this.repo.get(input.container,'container'),to=this.repo.get(input.destination);this.assertSite(c.location);this.assertSite(to.id);this.assertFree(c);requireRule(c.condition==='SERVICEABLE','Only serviceable stock can be moved for a request.');requireRule(c.location!==to.id||input.position,'Choose a different destination or an explicit reposition.');const from=this.repo.get(c.location);requireRule(['yard','site','truck'].includes(from.kind),'Finish the current handling task first.');
    let handling=from.kind==='truck'?this.repo.get(from.at):from;
    if(to.kind==='truck'){requireRule(to.at===handling.id,'The truck must be at this pickup location.');requireRule(to.destination===null||!input.site||to.destination===input.site,'One destination per truck trip.');}
    if(from.kind==='truck'){requireRule(['AT_YARD','AT_SITE'].includes(from.status)&&from.at===to.id,'Truck must arrive at the destination before unloading.');}
    requireRule(from.kind==='truck'||to.kind==='truck'||from.id===to.id,'Use a truck to move between a yard and site.');
    const candidate=input.position??this.positionFor(c,to.id),position={x:candidate.x,y:candidate.y,rotation:candidate.rotation??0,support:candidate.support??null};this.validatePlacement(c,to.id,position);
    const task=this.makeTask({type:'MOVE',container:c.id,from:c.location,to:to.id,handling:handling.id,position,request:null,actor:this.user.id,state:'QUEUED'});
    for(const line of this.repo.lines(c.id))this.reserve(c.id,line.product_id,line.quantity,task.id);
    return task;
  },
  makeTask(data){return this.repo.add('task',{...data,picked:false,resources:[],due:0,reason:null,createdAt:new Date().toISOString()});},
  reserve(container,product,quantity,task){const stock=this.repo.quantity(container,product),reserved=this.repo.all('reservation').filter(r=>r.active&&r.container===container&&r.product===product).reduce((s,r)=>s+r.quantity,0);requireRule(stock-reserved>=quantity,'INSUFFICIENT STOCK: another request has reserved these units.');return this.repo.add('reservation',{container,product,quantity,task,active:true});},
  request(input){const site=this.repo.get(input.site,'site');this.assertSite(site.id);requireRule(site.status==='ACTIVE','Choose an active site.');const product=this.effective(input.product);const quantity=integer(input.quantity,'Requested quantity',1,1000000);return this.repo.add('request',{site:site.id,product:product.id,quantity,status:'REQUESTED',allocated:0,delivered:0,actor:this.user.id,notes:input.notes??'',createdAt:new Date().toISOString()});},
  allocate(input){const request=this.repo.get(input.id,'request');requireRule(request.status==='REQUESTED','This request is already allocated or closed.');const truck=this.repo.get(input.truck,'truck');requireRule(truck.status==='AT_YARD','Truck must be at the yard.');this.assertTruckTrip(truck,request.site);const product=this.effective(request.product);requireRule(product.packQuantity!==null,'Full-pack quantity has not been configured.');const candidates=this.containers().filter(c=>c.location===truck.at&&!this.repo.all('resource').some(m=>m.cargo===c.id||m.drive?.container===c.id)&&c.condition==='SERVICEABLE'&&!this.containers().some(o=>o.support===c.id)&&!this.tasks().some(t=>active(t)&&(t.container===c.id||t.sourceContainer===c.id))&&this.repo.lines(c.id).length===1&&this.repo.quantity(c.id,product.id)>0).sort((a,b)=>{const aq=this.repo.quantity(a.id,product.id),bq=this.repo.quantity(b.id,product.id);return Number(bq===product.packQuantity)-Number(aq===product.packQuantity)||a.name.localeCompare(b.name)||a.id.localeCompare(b.id);});
    requireRule(candidates.reduce((sum,c)=>sum+this.repo.quantity(c.id,product.id),0)>=request.quantity,'INSUFFICIENT STOCK: no exact allocation is available.');
    let left=request.quantity;const tasks=[];
    for(const source of candidates){if(!left)break;this.assertCountFree(source);const quantity=Math.min(left,this.repo.quantity(source.id,product.id));let target=source,dependency=null;
      if(quantity<this.repo.quantity(source.id,product.id)){
        const empty=this.containers().find(c=>c.location===truck.at&&!this.repo.all('resource').some(m=>m.cargo===c.id||m.drive?.container===c.id)&&c.id!==source.id&&!this.repo.lines(c.id).length&&!c.support&&!this.containers().some(o=>o.support===c.id)&&!this.tasks().some(t=>active(t)&&t.container===c.id)&&c.condition==='SERVICEABLE');requireRule(empty,'A partial pack needs a real empty container in the yard. Add an empty container first.');this.assertCountFree(empty);
        target=empty;const repack=this.makeTask({type:'REPACK',container:empty.id,sourceContainer:source.id,product:product.id,quantity,from:truck.at,to:truck.at,handling:truck.at,position:{x:empty.x,y:empty.y,rotation:empty.rotation,support:null},request:request.id,actor:this.user.id,state:'QUEUED'});this.reserve(source.id,product.id,quantity,repack.id);dependency=repack.id;tasks.push(repack);
      }
      const extra=dependency?[{product_id:product.id,quantity}]:[];const position=this.positionFor(target,truck.id,extra);const task=this.makeTask({type:'MOVE',container:target.id,from:truck.at,to:truck.id,handling:truck.at,position,request:request.id,actor:this.user.id,state:'QUEUED',dependency});if(!dependency)this.reserve(source.id,product.id,quantity,task.id);tasks.push(task);left-=quantity;
    }
    truck.destination=request.site;this.repo.save(truck);request.status='ALLOCATED';request.allocated=request.quantity;request.truck=truck.id;this.repo.save(request);if(request.loadList){const list=this.repo.get(request.loadList,'loadList');if(!list.truck){list.truck=truck.id;this.repo.save(list);}}this.notify('Request allocated',`${request.quantity} × ${product.name} reserved for ${this.repo.get(request.site).name}.`,request.site);return {request,tasks};
  },
  cancel(input){const task=this.repo.get(input.id,'task');requireRule(active(task),'This task is already closed.');requireRule(!task.picked,'Cargo is on handling equipment. Resume placement; it cannot teleport back.');requireRule(!this.tasks().some(t=>active(t)&&t.dependency===task.id),'Cancel the dependent load first.');task.state='CANCELLED';this.repo.save(task);this.release(task);if(task.request){const request=this.repo.get(task.request,'request');request.status='PARTIALLY ALLOCATED';this.repo.save(request);}return task;},
  retry(input){const task=this.repo.get(input.id,'task');requireRule(task.state==='BLOCKED','Only blocked tasks can be retried.');task.state=task.resumeState??'RESERVED';task.reason=null;task.due=0;return this.repo.save(task);},
  release(task){for(const r of this.repo.all('reservation').filter(r=>r.task===task.id&&r.active)){r.active=false;this.repo.save(r);}for(const r of this.repo.all('resource').filter(r=>r.task===task.id)){r.task=null;this.repo.save(r);}},
  dispatch(input){const truck=this.repo.get(input.id,'truck'),destination=this.repo.get(input.destination??truck.destination);requireRule(['yard','site'].includes(destination.kind),'Choose a yard or site destination.');this.assertSite(destination.id);requireRule(destination.status!=='ARCHIVED','This destination is archived.');requireRule(['AT_YARD','AT_SITE'].includes(truck.status),'Truck is already travelling.');requireRule(truck.at!==destination.id,'Truck is already at this location.');requireRule(!this.tasks().some(t=>active(t)&&(t.to===truck.id||t.from===truck.id)),'Finish or cancel all loading tasks before departure.');for(const c of this.containers().filter(c=>c.location===truck.id)){this.assertCountFree(c);this.validatePlacement(c,truck.id,c);}requireRule(!this.repo.all('request').some(r=>r.truck===truck.id&&['ALLOCATED','PARTIALLY ALLOCATED'].includes(r.status)&&r.site!==destination.id),'This load is reserved for a different site.');const lists=this.repo.all('loadList').filter(l=>l.truck===truck.id&&!l.cancelled&&!l.delivery).map(l=>this.loadListView(l));requireRule(!lists.some(l=>l.lines.some(x=>x.status==='PARTIALLY ALLOCATED')),'A yard-list line is short because its loading task was cancelled. Cancel the yard list and re-list it before departure.');truck.status='IN_TRANSIT';truck.destination=destination.id;truck.remainingMs=3000;truck.travelActor=this.user.id;const delivery=this.repo.add('delivery',{truck:truck.id,from:truck.at,to:destination.id,status:'IN_TRANSIT',containers:this.containers().filter(c=>c.location===truck.id).map(c=>c.id),createdAt:new Date().toISOString()});truck.delivery=delivery.id;this.repo.save(truck);for(const view of lists){const list=this.repo.get(view.id,'loadList');list.delivery=delivery.id;list.departedAt=delivery.createdAt;list.lines=list.lines.map(line=>({...line,sent:view.lines.find(x=>x.product===line.product)?.loaded??0}));this.repo.save(list);}this.notify('Truck departed',`${truck.name} is travelling to ${destination.name}.`,destination.kind==='site'?destination.id:null);return truck;},
  unload(input){const truck=this.repo.get(input.id,'truck');requireRule(['AT_SITE','AT_YARD'].includes(truck.status),'Truck must arrive before unloading.');const tasks=[];const cargo=this.containers().filter(c=>c.location===truck.id).sort((a,b)=>Number(!!b.support)-Number(!!a.support));for(const c of cargo){if(this.containers().some(o=>o.support===c.id))continue;if(this.tasks().some(t=>active(t)&&t.container===c.id))continue;tasks.push(this.queue({container:c.id,destination:truck.at}));}requireRule(tasks.length,'No accessible cargo to unload. Finish the top containers first.');return tasks;},
  returnStock(input){const c=this.repo.get(input.container,'container');this.assertSite(c.location);const location=this.repo.get(c.location);requireRule(location.kind==='site','Select a container at the site.');const truck=this.repo.get(input.truck,'truck');requireRule(truck.at===location.id&&truck.status==='AT_SITE','Send an empty truck to this site first.');return this.queue({container:c.id,destination:truck.id});},
  plannedPath(task,c){const loc=this.repo.get(task.handling),from=this.repo.get(task.from),to=this.repo.get(task.to);const source=task.type==='REPACK'?this.repo.get(task.sourceContainer,'container'):c;const start=from.kind==='truck'?loc.loading:{x:source.x,y:source.y},end=to.kind==='truck'?loc.loading:task.position;const obstacles=[...this.containers().filter(o=>o.location===loc.id&&o.id!==c.id&&o.id!==task.sourceContainer&&o.id!==c.support&&o.id!==task.position.support).map(o=>rect(o)),...this.fixtureObstacles(loc)];const shape=rect(c);shape.w=Math.max(1500,shape.w);shape.h=Math.max(1000,shape.h);const path=route(start,end,shape,loc.points,obstacles);requireRule(path,'No clear path for the machine and load. Relocate blocking containers first.');return path;}
};
