import {forkliftMethods} from './domain/forklifts.js';
import {workerMethods} from './domain/workers.js';
import { randomUUID,createHash } from 'node:crypto';
import { Repository } from './repository.js';
import { Service,AppError } from './service.js';
import { atomic } from './database.js';
import { requireRule,integer } from './domain/geometry.js';
import { catalogueMethods } from './domain/catalogue.js';
import { inventoryMethods,active } from './domain/inventory.js';
import { logisticsMethods } from './domain/logistics.js';
import { movementMethods } from './domain/movement.js';
import { materialsMethods } from './domain/materials.js';
import { fleetMethods } from './domain/fleet.js';
import { layoutMethods } from './domain/layout.js';
import { jobMethods } from './domain/jobs.js';
const operational=['workerSkills','createJob','assignJob','nextJob','takeOffJob','cancelJob','jobsMode','siteDetails','fixtures','commitLayout','cancelLayout','siteBoundary','retire','scrapContainer','quickAdjust','allocateLoadList','workerCommand','parking','yard','container','containerSettings','product','override','seed','importCatalogue','site','archive','truck','resources','queue','allocate','cancel','retry','dispatch','unload','condition','pause','count','observe','cancelCount'];
export class Simulation {
  constructor(db,user){this.db=db;this.user=user;this.auth=new Service(db);this.repo=new Repository(db,user.company_id);}
  assertSite(id){if(this.auth.permissions(this.user).includes('operations.manage'))return;const object=this.repo.get(id);let site=object;if(object.kind==='container')site=this.repo.get(object.location);if(object.kind==='truck')site=this.repo.get(object.at);requireRule(site.kind==='site'&&site.supervisor===this.user.id,'You can only access your assigned sites.');}
  execute(action,input,key){
    requireRule(typeof key==='string'&&key.length>=8&&key.length<=150,'A valid idempotency key is required.');
    if(operational.includes(action))this.auth.require(this.user,'operations.manage');
    else if(['opening','purchase','stockIntake','stockRemoval','removeStock','purgeDemo','approveCount'].includes(action))this.auth.require(this.user,'stock.adjust');
    else if(['request','returnStock','cancelRequest','createLoadList','cancelLoadList'].includes(action))this.auth.require(this.user,'requests.create');
    else throw new AppError(404,'Unknown command.');
    const fingerprint=createHash('sha256').update(JSON.stringify({actor:this.user.id,action,input})).digest('hex');this.key=key;
    return atomic(this.db,()=>{const previous=this.db.prepare('SELECT * FROM commands WHERE company_id=? AND key=?').get(this.user.company_id,key);if(previous){requireRule(previous.fingerprint===fingerprint,'This idempotency key was used for a different action.');return JSON.parse(previous.result);}const result=this[action](input);this.repo.event(this.user.id,'COMMAND',{reason:action,key});this.db.prepare('INSERT INTO commands VALUES(?,?,?,?)').run(this.user.company_id,key,fingerprint,JSON.stringify(result??{ok:true}));return result;});
  }
  pause(input){let config=this.repo.all('config')[0];requireRule(config,'Configure yard resources first.');requireRule(typeof input.paused==='boolean','Choose pause or resume.');config.paused=input.paused;return this.repo.save(config);}
  notify(title,body,site){return this.repo.add('notification',{title,body,site,createdAt:new Date().toISOString(),provider:'IN_APP_ONLY'});}
  tripOf(id,visible){if(!id)return null;try{const d=this.repo.get(id,'delivery');return {id:d.id,status:d.status,completedAt:d.completedAt??null,to:visible(d.to)?d.to:null,from:visible(d.from)?d.from:null};}catch{return null;}}
  supervisorName(id){return id?this.db.prepare('SELECT name FROM users WHERE id=?').get(id)?.name??null:null;}
  snapshot(page=0){
    integer(page,'Container page',0,1000000);
    const operations=this.auth.permissions(this.user).includes('operations.manage');const sites=this.repo.all('site').filter(s=>operations||s.supervisor===this.user.id);const siteIds=new Set(sites.map(s=>s.id));
    const allTrucks=this.repo.all('truck'),allDeliveries=this.repo.all('delivery');const trucks=allTrucks.filter(t=>!t.retired&&(operations||siteIds.has(t.at)||siteIds.has(t.destination)));const lastAt=new Map();for(const d of allDeliveries)if(d.status==='DELIVERED'&&d.completedAt&&(!lastAt.has(d.to)||d.completedAt>lastAt.get(d.to)))lastAt.set(d.to,d.completedAt);const truckIds=new Set(trucks.map(t=>t.id));
    const allTasks=this.tasks(),liveTasks=allTasks.filter(active),visible=id=>operations||siteIds.has(id),depStarted=x=>!!x.dependency&&allTasks.some(d=>d.id===x.dependency&&d.state!=='CANCELLED'&&(d.machine||d.picked));const tasks=allTasks.filter(t=>operations||siteIds.has(t.handling));const machineIds=new Set(tasks.filter(t=>t.picked&&active(t)).map(t=>t.machine));
    const allContainers=this.containers().filter(c=>operations||siteIds.has(c.location)||truckIds.has(c.location)||machineIds.has(c.location));
    const reservations=this.repo.all('reservation').filter(r=>r.active);
    const allBalances=allContainers.flatMap(c=>this.repo.lines(c.id).map(l=>({...l,container:c.id,location:c.location,condition:c.condition,reserved:reservations.filter(r=>r.container===c.id&&r.product===l.product_id).reduce((s,r)=>s+r.quantity,0)})));
    const containers=allContainers.slice(page*100,(page+1)*100),ids=new Set(containers.map(c=>c.id)),balances=allBalances.filter(l=>ids.has(l.container));
    const result={mode:'SIMULATION / DEMONSTRATION',yards:operations?this.repo.all('yard'):[],sites:sites.map(s=>({...s,supervisorName:this.supervisorName(s.supervisor),lastDeliveryAt:lastAt.get(s.id)??null})),trucks,containers,balances,products:this.effectiveProducts(),tasks:tasks.filter(t=>active(t)).slice(0,100).map(t=>({...t,...this.taskInfo(t)})),recentTasks:tasks.filter(t=>!active(t)).slice(-20).map(t=>({...t,...this.taskInfo(t)})),requests:this.repo.all('request').filter(r=>operations||siteIds.has(r.site)),resources:this.repo.all('resource').filter(r=>r.enabled&&(operations||siteIds.has(r.location))),counts:operations?this.repo.all('count').slice(-30):[],config:this.repo.all('config')[0]??null,notifications:this.repo.all('notification').filter(n=>operations||siteIds.has(n.site)).slice(-10),sources:this.repo.all('source'),packaging:this.repo.all('packaging'),deliveries:allDeliveries.filter(d=>operations||siteIds.has(d.to)||siteIds.has(d.from)).slice(-30)};
    result.availability={stillages:allContainers.filter(c=>c.type!=='CAGE').length,cages:allContainers.filter(c=>c.type==='CAGE').length,serviceablePieces:allBalances.filter(l=>l.condition==='SERVICEABLE').reduce((s,l)=>s+l.quantity-l.reserved,0)};result.resources=result.resources.map(r=>r.type==='WORKER'?{...r,...this.workerPosition(r)}:r.type==='FORKLIFT'?{...r,...this.forkliftPosition(r),cargoPreview:r.cargo?this.repo.get(r.cargo,'container'):null}:r);result.register=this.register(allBalances,result.products);result.stock=this.stockByLocation(allBalances,allContainers,result.products);const today=new Date().toDateString(),payloadOf=new Map(allTrucks.map(t=>[t.id,t.payload]));result.runsToday={heavy:0,light:0};for(const d of allDeliveries){if(d.status!=='DELIVERED'||!d.completedAt||!(siteIds.has(d.to)||siteIds.has(d.from))||new Date(d.completedAt).toDateString()!==today)continue;const payload=payloadOf.get(d.truck);if(payload!==undefined)result.runsToday[payload>=10000000?'heavy':'light']++;}result.additions=this.stockLog('additions');result.removals=this.stockLog('removals');result.loadLists=this.loadLists();result.layouts=operations?this.layouts():[];if(operations){const yardIds=new Set(result.yards.map(y=>y.id));const jv=this.jobsView(yardIds);result.jobs=jv.jobs;result.recentJobs=jv.recentJobs;result.skillCatalogue=this.skillCatalogue();result.ladder={};const boards=new Map();for(const y of result.yards){result.ladder[y.id]=this.ladderView(y,result.jobs,result.tasks);for(const [id,b] of this.workerBoards(y,result.resources.filter(r=>r.type==='WORKER'&&r.location===y.id),result.jobs,result.tasks))boards.set(id,b);}result.resources=result.resources.map(r=>r.type==='WORKER'?{...r,skills:this.normalisedSkills(r),board:boards.get(r.id)??null}:r);}else result.resources=result.resources.map(r=>r.type==='WORKER'?{...r,skills:this.normalisedSkills(r)}:r);const byDelivery=new Map();for(const l of result.loadLists)if(l.delivery)byDelivery.set(l.delivery,[...(byDelivery.get(l.delivery)??[]),l]);result.deliveries=result.deliveries.map(d=>({...d,manifest:byDelivery.get(d.id)??[]}));result.containerCount=allContainers.length;result.page=page;result.pageSize=100;result.stockTotal=allBalances.reduce((s,l)=>s+l.quantity,0);result.reservedTotal=allBalances.reduce((s,l)=>s+l.reserved,0);
    result.trucks=result.trucks.map(t=>{const loaded=allContainers.filter(c=>c.location===t.id),reserved=this.occupied(t.id).filter(c=>!loaded.some(l=>l.id===c.id));const mass=list=>{try{return list.reduce((sum,c)=>sum+this.projectedWeight(c),0);}catch{return null;}};return {...t,loadedWeight:mass(loaded),reservedWeight:mass(reserved),deckArea:loaded.filter(c=>!c.support).reduce((s,c)=>s+c.envelopeLength*c.envelopeWidth,0),tasksTo:liveTasks.filter(x=>x.to===t.id).length,tasksStarted:liveTasks.filter(x=>x.to===t.id&&(x.machine||x.picked||depStarted(x))).length,tasksFrom:liveTasks.filter(x=>x.from===t.id).length,trip:this.tripOf(t.delivery,visible)};});return result;
  }
  history(limit=100,after=0){integer(limit,'Page size',1,200);integer(after,'History cursor',0,Number.MAX_SAFE_INTEGER);return this.scopedHistory(limit,after);}
  scopedHistory(limit,after){if(this.auth.permissions(this.user).includes('operations.manage'))return this.repo.history(limit,after);return this.db.prepare(`SELECT l.* FROM ledger l WHERE l.company_id=? AND l.sequence>? AND EXISTS(SELECT 1 FROM objects s WHERE s.company_id=l.company_id AND s.kind='site' AND json_extract(s.data,'$.supervisor')=? AND (s.id=l.source OR s.id=l.destination OR EXISTS(SELECT 1 FROM objects t WHERE t.company_id=l.company_id AND t.id=l.task_id AND json_extract(t.data,'$.handling')=s.id))) ORDER BY l.sequence LIMIT ?`).all(this.user.company_id,after,this.user.id,limit);}
  export(kind){const snapshot=this.snapshot();const name=id=>snapshot.products.find(p=>p.id===id)?.name??id;if(kind==='register'){return csv([['Product','System','Category','In yard','At sites','On trucks','Total','Reserved','Available','Containers'],...snapshot.register.map(r=>[r.name,r.system,r.category,r.yard,r.site,r.truck,r.quantity,r.reserved,r.available,r.containers])]);}if(kind==='additions'||kind==='removals'){return csv([['Sequence','Event','Product','Container','Quantity','Location','Reason','Time'],...this.stockLog(kind,1000).map(l=>[l.sequence,l.event,name(l.product_id),l.container_id,l.quantity,l.destination??l.source,l.reason,l.created_at])]);}if(kind==='yardlist'){return csv([['Yard list','Status','Site','Truck','Product','Requested','Reserved','Loaded','Delivered','Line status'],...snapshot.loadLists.flatMap(l=>l.lines.map(x=>[l.name,l.status,l.site,l.truckName,x.name,x.quantity,x.reserved,x.loaded,x.delivered,x.status]))]);}if(kind==='stock'){for(let page=1;page*100<snapshot.containerCount;page++){const next=this.snapshot(page);snapshot.balances.push(...next.balances);snapshot.containers.push(...next.containers);}const rows=[['Product','Container','Location','Condition','Physical quantity','Reserved quantity'],...snapshot.balances.map(l=>[snapshot.products.find(p=>p.id===l.product_id)?.name,snapshot.containers.find(c=>c.id===l.container)?.name,l.location,l.condition,l.quantity,l.reserved])];return csv(rows);}return csv([['Sequence','Event','Product','Container','Quantity','From','To','Reason','Time'],...this.scopedHistory(10000,0).map(l=>[l.sequence,l.event,l.product_id,l.container_id,l.quantity,l.source,l.destination,l.reason,l.created_at])]);}
}
Object.assign(Simulation.prototype,catalogueMethods,inventoryMethods,logisticsMethods,movementMethods,workerMethods,forkliftMethods,materialsMethods,fleetMethods,layoutMethods,jobMethods);
function csv(rows){return rows.map(row=>row.map(value=>'"'+String(value??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');}

export function startScheduler(db){
  const owner=randomUUID(),now=Date.now();
  atomic(db,()=>{const lease=db.prepare('SELECT * FROM engine_lease WHERE id=1').get();requireRule(!lease||lease.expires_at<now,'Another movement engine is running for this database.');db.prepare('INSERT INTO engine_lease VALUES(1,?,?) ON CONFLICT(id) DO UPDATE SET owner=excluded.owner,expires_at=excluded.expires_at').run(owner,now+5000);});
  // Timers advance only their fixed quantum. No elapsed downtime is replayed.
  const timer=setInterval(()=>{try{atomic(db,()=>{const lease=db.prepare('SELECT owner FROM engine_lease WHERE id=1').get();requireRule(lease?.owner===owner,'Movement engine lease lost.');db.prepare('UPDATE engine_lease SET expires_at=? WHERE owner=?').run(Date.now()+5000,owner);for(const row of db.prepare('SELECT ur.company_id,ur.user_id id FROM user_roles ur WHERE ur.role=? GROUP BY ur.company_id').all('OWNER'))new Simulation(db,row).tick(250);});}catch(error){console.error(JSON.stringify({event:'scheduler_error',message:error.message}));}},250);timer.unref();
  return ()=>{clearInterval(timer);db.prepare('DELETE FROM engine_lease WHERE owner=?').run(owner);};
}
